### ISSUE TITLE
Mara War Game

### ISSUE THREAD

**Issue by marasanders** [ga-dc/project1-gallery#10]
Link to repo: https://github.com/marasanders/War-Card-Game
Link to deployed app: http://marasanders.github.io/War-Card-Game/

Things you'd like specific feedback on: The best approach when doing a project to balance gold level future code with bronze level code. In other words when I was coding my bronze level I had an eye on the gold and it was distracting me and causing me to put in some things I never ended up using and some things that it was a good idea to put in there because it made gold easier. How do you strike the balance?

**Comment by RobertAKARobin** [comment]
# Project Feedback + Evaluation

| Score | Expectations |
| --- | --- |
| 0 | Incomplete |
| 1 | Progressing |
| 2 | Performing |
| 3 | Excelling |

## Project Workflow: 2

> Did you complete the user stories, wireframes, task tracking, and/or ERDs, as specified above? Did you use source control as expected for the phase of the program you’re in?

## Technical Requirements: 2

> Did you deliver a project that met all the technical requirements? Given what the class has covered so far, did you build something that was reasonably complex?

## Code Quality: 2

> Did you follow code style guidance and best practices covered, such as spacing, modularity, and semantic naming? Did you comment your code?

## Creativity/Interface: 2

> Is your user interface easy to use and understand? Does it make sense for the problem you're solving? Does your interface demonstrate creative design?

## Overall: 2

Nice job, Mara! Your immaculately-formatted code is always a breath of fresh air.

I think we discussed the gold-versus-bronze thing last week, but to reiterate: your best bet is to keep a piece of paper or a text page open nearby so when an idea occurs to you it can be written down.

There's a famous programming saying: "Weeks of planning can save hours of coding." That is: when you're thinking about down-the-road so much, it's really easy to unnecessarily overcomplicate what you're working on now. The point of the bronze/silver/gold thing is that you JUST focus on bronze, then JUST focus on silver, then JUST focus on gold. At each stage you have a functioning app.
