### ISSUE TITLE
Wes Coffay- Towers of Hanoi

### ISSUE THREAD

**Issue by justwes2** [ga-dc/project1-gallery#102]
Link to repo: https://github.com/justwes2/ga-project-1/tree/gh-pages
Link to deployed app:https://justwes2.github.io/ga-project-1/

Things you'd like specific feedback on:
- I feel like my style choices were not as dynamic as I would have liked, however, I am unsure what would have given a more intuitive feel to the design. 
- For the create discs function, I was able to implement the input selector, however, the code for creating that actual divs was not DRY. I could not figure out a loop that would cycle through the 7 div ids only as many times as it was called (I tried a for i<input loop, but i was unable to get it to iterate over the disc divs correctly.

**Comment by amaseda** [comment]
Left some comments here: https://github.com/justwes2/ga-project-1/pull/1
