### ISSUE TITLE
Project 1: Tower of Hanoi - Elena Santana

### ISSUE THREAD

**Issue by fanelenan7** [ga-dc/project1-gallery#103]
Link to repo: https://github.com/fanelenan7/towers-of-hanoi/tree/gh-pages
Link to deployed app: https://fanelenan7.github.io/towers-of-hanoi/

Things you'd like specific feedback on: 
How aesthetically appealing is the final version? Is it good enough to use on a designer+developer resume? 

Is there a way to list objects to append in order without listing each and every one in the order I want? - that is the portion of the code I'm most unsatisfied with, as it limits the scalability.

I also am not as comfortable with hovers, and had to list them under separate listeners. Don't know if I can dry that up as well, that's a lot of repeats.

**Comment by amaseda** [comment]
Left some comments here: https://github.com/fanelenan7/towers-of-hanoi/pull/1/
