### ISSUE TITLE
Bill Bobbitt - Flash Cards

### ISSUE THREAD

**Issue by wmbobbitt** [ga-dc/project1-gallery#104]
Link to repo: https://github.com/wmbobbitt/flash-card-project-1/tree/gh-pages
Link to deployed app: https://wmbobbitt.github.io/flash-card-project-1/

Things you'd like specific feedback on:
- Where my code could be cleaner
- Where I could use tricks I didn't
- Anything that was 'basic' and could be elevated!

**Comment by amaseda** [comment]
Take a look at my comments here: https://github.com/wmbobbitt/flash-card-project-1/pull/1
