### ISSUE TITLE
Project 1 Eric Green

### ISSUE THREAD

**Issue by ericcgreen** [ga-dc/project1-gallery#106]
Link to repo: https://github.com/ericcgreen/eric_green_project1
Link to deployed app: https://ericcgreen.github.io/eric_green_project1

Things you'd like specific feedback on: 

- Better ways to help understand functions.

- What's the best practice to get your pseudocode to actual code?

- How to clean up my code: input on refactoring and knowing when to stop and continue doing it.

completeness: 4/5
comfort: 2/5

**Comment by avalant** [comment]
Left comments in garnet and also slacked some resources.
