### ISSUE TITLE
Feed the Cookie Monster

### ISSUE THREAD

**Issue by evalaidc** [ga-dc/project1-gallery#107]
Link to repo: https://github.com/evalaidc/project1
Link to deployed app: https://evalaidc.github.io/project1/

Things you'd like specific feedback on:
 Please include feedback on the readme.md specifically the user stories. I would also like feedback on the javascript/ use of $(this).

Thanks.

**Comment by avalant** [comment]
Feedback for your project one has been left in garnet.
