### ISSUE TITLE
Savraj Singh Project 1

### ISSUE THREAD

**Issue by SavrajSingh** [ga-dc/project1-gallery#111]
Link to repo: https://github.com/SavrajSingh/Project-1
Link to deployed app: https://github.com/SavrajSingh/Project-1/tree/gh-pages

Things you'd like specific feedback on: What I should Improve on. I want to be the best dev I can be. Thanks again for all the help.

**Comment by amaseda** [comment]
Left some comments here: https://github.com/SavrajSingh/Project-1/pull/1
