### ISSUE TITLE
Dan Lin Project 1

### ISSUE THREAD

**Issue by dlin2102** [ga-dc/project1-gallery#113]
Link to repo: https://github.com/dlin2102/1project
Link to deployed app: https://dlin2102.github.io/1project/

Things you'd like specific feedback on:
Additional features I could've added.

**Comment by dlin2102** [comment]
And by that, I mean js. That was by the far, the hardest part of this project.

**Comment by AndyWhitley** [comment]
👍 Check out the PR on your project repo for feedback
