### ISSUE TITLE
Taylor Scott Project 01

### ISSUE THREAD

**Issue by taylorscott91** [ga-dc/project1-gallery#116]
Link to repo: https://github.com/taylorscott91/project01/
Link to deployed app: https://taylorscott91.github.io/project01/

Things you'd like specific feedback on:
Fixing this penalty system, for one. Also, figuring out how to hide the "Correct!" message when you pull up a new question.

**Comment by AndyWhitley** [comment]
👍 Check out the PR on your project repo for feedback. Great work!
