### ISSUE TITLE
Bedig Galladian-US Citizenship Quiz

### ISSUE THREAD

**Issue by bgalladian** [ga-dc/project1-gallery#119]
Link to repo: https://github.com/bgalladian/project-01
Link to deployed app: https://bgalladian.github.io/project-01/

Things you'd like specific feedback on:

Very basic, and minimal coding.  Would love to implement features in the future such as location based question (i.e local congressman/representatives).  Overall understanding javascript more and more each day, but would love any more tips on how to start being able to create and generate it more and more.

**Comment by AndyWhitley** [comment]
👍 See PR on project repo for feedback
