### ISSUE TITLE
Hangman - Hannah Schuster

### ISSUE THREAD

**Issue by hschuster9** [ga-dc/project1-gallery#122]
Link to repo: https://github.com/hschuster9/project1
Link to deployed app: https://hschuster9.github.io/project1/

Things you'd like specific feedback on:

-how to handle a letter input that has already been guessed
-how to handle non letter inputs
-if I could have broken up the functions instead of having two long ones
-better way to organize/write the code

**Comment by avalant** [comment]
Feedback has been left in garnet for your project.
