### ISSUE TITLE
Ebenezer | Project 1 | Travel Trivia

### ISSUE THREAD

**Issue by ebenezerw** [ga-dc/project1-gallery#124]
Link to repo: https://github.com/ebenezerw/Project1_TravelTrivia
Link to deployed app: https://ebenezerw.github.io/Project1_TravelTrivia/

Things you'd like specific feedback on:
I'd like feedback on how to best handle scoring. Also, any pointers for changing the color of a specific answer as I hover or select it. I could only get this to work at the same time on all the answers displayed on the page. Also, any tips for using jQuery plug ins.

**Comment by avalant** [comment]
Feedback left in garnet.
