### ISSUE TITLE
War and Pokemon

### ISSUE THREAD

**Issue by AT89** [ga-dc/project1-gallery#13]
Link to repo: https://github.com/AT89/WARCARDGAME
Link to deployed app: http://at89.github.io/WARCARDGAME/

5/5 comfort level - i feel very good about my current skills and have come very far from 2 weeks ago.
5/5 completeness

Things you'd like specific feedback on:
-how to clean up my javascript
    -making use of vars to shorten up the JS
   -Repeating code for p1 and p2
         -Ways to utilize the .this so i can add game modes on top of existing game
         -Easier way to deploy the Pokemon mode (coding wise)
    -I might have needed to do a document ready
   -Any other suggestions?

**Comment by AT89** [comment]
New specifics questions:
-I want to hide the players hand until a setTimeout (akin to making all the changes happen during the drop of the song). When I put in    `$("#p2Holder").html("");` in console, it actually clears the hand. Similar to the method I used to clear the hand and rebuild it based off the click functions, I need it to clear and then rebuild the hand (as Pokeballs). However, the way the hand is built is different than how the other parts of the page are built, the img is inserted in the JS through append : 

Line 196

```
 $("#p2Holder").append("<div class='p2Hand'> <img class='card' src='pokemon/pokeball.png'/></div>");
            i++;
```

I tried several ways the night prior to do it but I couldn't get it to hide properly. I used a boolean pokeFirst so that it would only happen on the first occurence (if true.. set pokeFirst to false, else do normal stuff). Would you have any suggestions on how to do this?

**Comment by RobertAKARobin** [comment]
# Project Feedback + Evaluation

| Score | Expectations |
| --- | --- |
| 0 | Incomplete |
| 1 | Progressing |
| 2 | Performing |
| 3 | Excelling |

## Project Workflow: 3

> Did you complete the user stories, wireframes, task tracking, and/or ERDs, as specified above? Did you use source control as expected for the phase of the program you’re in?

## Technical Requirements: 2

> Did you deliver a project that met all the technical requirements? Given what the class has covered so far, did you build something that was reasonably complex?

## Code Quality: 1

> Did you follow code style guidance and best practices covered, such as spacing, modularity, and semantic naming? Did you comment your code?

**You have to keep your indentation consistent, and semantically name your variables.** No more of this `var t` business. This is **not** something you can retroactively add to your code. You must be doing it from the start.

Great job commenting your code!

## Creativity/Interface: 3

> Is your user interface easy to use and understand? Does it make sense for the problem you're solving? Does your interface demonstrate creative design?

## Overall: 2

See my inline code comments: https://github.com/AT89/WARCARDGAME/pull/2/files

Nice job! This is REALLY complex code, and I think learning object-oriented Javascript will go a long way toward simplifying and streamlining it.

To answer some of your specific questions, that weren't answered in my code comments:
- Vars don't really shorten your code...?
- I don't think `.this` will help you add modes
