### ISSUE TITLE
Trivia game-Habtamu Abele-CR6

### ISSUE THREAD

**Issue by HabRonan** [ga-dc/project1-gallery#132]
Link to repo: https://github.com/HabRonan/project-1
Link to deployed app: https://habronan.github.io/project-1/

Things you'd like specific feedback on: 
 what do you think about the game?
Instructor- what do you think about the game and the techs used?

**Comment by amaseda** [comment]
Take a look at my notes here! https://github.com/HabRonan/project-1/pull/1
