### ISSUE TITLE
Mitchell Carroll (Project 1)

### ISSUE THREAD

**Issue by mitchellcarroll** [ga-dc/project1-gallery#133]
Link to repo: https://github.com/mitchellcarroll/mitchellcarroll.github.io-hangman
Link to deployed app: mitchellcarroll.github.io-hangman

Things you'd like specific feedback on:
I need help looking at my functions that contain if & else statements. My game does not fully work.

**Comment by AndyWhitley** [comment]
👍 Please refer to the PR on your project repo for feedback. Also, add the correct url for your app on github pages: mitchellcarroll.github.io/hangman3
