### ISSUE TITLE
Project1-Clements-Tower

### ISSUE THREAD

**Issue by sdkclements** [ga-dc/project1-gallery#134]
Link to repo: https://github.com/sdkclements/GA-Project1
Link to deployed app: https://sdkclements.github.io/GA-Project1/

Things you'd like specific feedback on:
my event listeners, and if there is a better way to organize them because i feel they got a bit out of control. Also what is the best way to click on child elements when inside a element with a .onclick
---
The best way to solve my if/ statements, is it bad practice to compare a chain of jquery methods like in my last bit of code. should i set vars equal to them and then compare?

**Comment by amaseda** [comment]
Left some comments here: https://github.com/sdkclements/GA-Project1/pull/1
