### ISSUE TITLE
Katherine Ehni Project 1

### ISSUE THREAD

**Issue by ehnik** [ga-dc/project1-gallery#140]
Link to repo: https://github.com/ehnik/project1
Link to deployed app: https://ehnik.github.io/project1/

Things you'd like specific feedback on:
--why the drop function for the UI widget consistently dropped the draggable element at the very bottom of the container
--how to more precisely/simply expand the pole containers so that they touch (but don't overlap)--as of now, i just did my best guess with pixels

**Comment by AndyWhitley** [comment]
👍 See project repo for feedback
