### ISSUE TITLE
Math Trivia - Ammar Alasadi

### ISSUE THREAD

**Issue by ammaralasadi1** [ga-dc/project1-gallery#146]
Link to repo: https://github.com/ammaralasadi1/Project-1-
Link to deployed app: https://ammaralasadi1.github.io/Project-1-/

Things you'd like specific feedback on:
1 - How to add a User and Have the user name stored, I tried it with local storage but had difficulties.

**Comment by AndyWhitley** [comment]
Please refer to the PR on your project's repository for detailed feedback. 

Great work 👍
