### ISSUE TITLE
Hali Bakarr Trivia Game

### ISSUE THREAD

**Issue by utamilah** [ga-dc/project1-gallery#154]
Link to repo: https://github.com/utamilah/trivia-game/tree/gh-pages
Link to deployed app: https://utamilah.github.io/trivia-game/

Things you'd like specific feedback on: 
My js... is my JS code too confusing? How about the order of things? I couldn't figure out how to use what we've learned so far to make my JS more simple. (Especially in terms of the switch case).

**Comment by AndyWhitley** [comment]
Please see the PR on your project 1 repository for feedback. Great work 👍
