### ISSUE TITLE
Project 1

### ISSUE THREAD

**Issue by mattpcaplan** [ga-dc/project1-gallery#157]
Link to repo: https://github.com/mattpcaplan/WDIProject1
Link to deployed app: https://mattpcaplan.github.io/WDIProject1

Things you'd like specific feedback on:

**Comment by mattpcaplan** [comment]
Im having issues deploying.  I have project locally.

**Comment by AndyWhitley** [comment]
Please refer to the PR on your project 1 repo for feedback. Also, please come to us during office hours or schedule a one on one for assistance with deployment. 

Great work 👍
