### ISSUE TITLE
Julia Schultz Concentration Game

### ISSUE THREAD

**Issue by jschultz21** [ga-dc/project1-gallery#16]
Link to repo: https://github.com/jschultz21/JschultzConcentration/tree/gh-pages
Link to deployed app: http://jschultz21.github.io/JschultzConcentration/

Things you'd like specific feedback on:
1. ways I could dry up my code
2. decreasing the length  of my one really long function
3.  using css to arrange the gameboard and deckchoice divs so that deckchoice can't go beneath gameboard when browser width is decreased

**Comment by RobertAKARobin** [comment]
# Project Feedback + Evaluation

| Score | Expectations |
| --- | --- |
| 0 | Incomplete |
| 1 | Progressing |
| 2 | Performing |
| 3 | Excelling |

## Project Workflow: 2

> Did you complete the user stories, wireframes, task tracking, and/or ERDs, as specified above? Did you use source control as expected for the phase of the program you’re in?

## Technical Requirements: 2

> Did you deliver a project that met all the technical requirements? Given what the class has covered so far, did you build something that was reasonably complex?

## Code Quality: 1

> Did you follow code style guidance and best practices covered, such as spacing, modularity, and semantic naming? Did you comment your code?

## Creativity/Interface: 3

> Is your user interface easy to use and understand? Does it make sense for the problem you're solving? Does your interface demonstrate creative design?

## Overall: 2

My inline code comments: https://github.com/jschultz21/JschultzConcentration/pull/3/files

Nice job, Julia! You did a great job of commenting your code. I'd like to see you take it to the next level by extracting more stuff into functions, like this:

https://github.com/jschultz21/JschultzConcentration/pull/3/files#diff-0364f57fbff2fabbe941ed20c328ef1aR138

Also, when you find yourself with an `if/else` block that's really long, I recommend extracting each possible outcome into its own function as well to improve readability.

I'd encourage you to work on how things are physically organized in your JS file. I like to put all my functions together, and put all the code that runs when the page is initialized (including event listeners) somewhere else, ideally in `$(document).ready`. 

As for keeping the deckchoice divs from going under the board, try to avoid using absolute positioning and **especially** floating unless absolutely necessary. Flexbox may be helpful here.
