### ISSUE TITLE
[Trivia] GA- Project 1

### ISSUE THREAD

**Issue by Fitssum** [ga-dc/project1-gallery#164]
Link to repo: https://fitssum.github.io/Fun-Trivia-/
Link to deployed app: https://github.com/Fitssum/Fun-Trivia-/tree/gh-pages

Things you'd like specific feedback on: 
- I would like to know how I can stop the counter. 
- One more thing, even though I put .val() to relate the question with the answer, it returns false for a correct answer when the answer is not Capitalized..Is it possible to have a correct response regardless of the the font style?

**Comment by superbuggy** [comment]
comments here: https://gist.github.com/5f11eda73b784ebd12314094bfaaa4c8
Well done!
