### ISSUE TITLE
Mark - Tower of Hanoi

### ISSUE THREAD

**Issue by mjm5vp** [ga-dc/project1-gallery#171]
Link to repo:  https://github.com/mjm5vp/Tower-of-Hanoi/tree/gh-pages
Link to deployed app:  https://mjm5vp.github.io/Tower-of-Hanoi/

Things you'd like specific feedback on:
I started off well by doing OOP using objects on the tower and user plus a class for the blocks, but soon started adding functions on to the end and using a lot of global variables.  Does the structure of my code seem reasonable or should it be more object oriented.  What is the main downside of using a lot of global variables, as long as they are uniquely identified.

**Comment by nayana487** [comment]
See my comments in the PR to your app.
