### ISSUE TITLE
perry fustero simon

### ISSUE THREAD

**Issue by perryf** [ga-dc/project1-gallery#177]
Link to repo: https://github.com/perryf/simonpiano
Link to deployed app: https://perryf.github.io/simonpiano/

Things you'd like specific feedback on:
Ways to clean up my code/ make it more professional.
User experience, likes/dislikes, ideas to improve/implement.

**Comment by AndyWhitley** [comment]
Great job on this project. Please refer to the Pull Request on your project's repo for feedback:
https://github.com/perryf/simonpiano/pull/1
👍
