### ISSUE TITLE
Alex W Project 1

### ISSUE THREAD

**Issue by awandres** [ga-dc/project1-gallery#178]
Link to repo: https://github.com/awandres/simon
Link to deployed app: https://awandres.github.io/simon/

Things you'd like specific feedback on:
Mostly I'd like to know if there were ways to perform the tasks in a simpler, more streamlined way. I was able to get the functionality how I wanted it, but it seemed clunky and not very DRY

Also, I felt like I used a lot of global variables. Variables kept getting updated, and then used elsewhere in different functions, so I had to make sure the new values transferred over. Since we're told global variables are bad, how would I get around that?

**Comment by juancgarcia** [comment]
Great job! Please refer to the Pull Request on your project repo for feedback: 
https://github.com/awandres/simon/pull/1
👍
