### ISSUE TITLE
Tower-Of-Hanoi

### ISSUE THREAD

**Issue by TimGafvert** [ga-dc/project1-gallery#179]
Link to repo: https://github.com/TimGafvert/Towers-Of-Hanoi
Link to deployed app: https://timgafvert.github.io/Towers-Of-Hanoi/

Things you'd like specific feedback on:
DRYing my code

**Comment by juancgarcia** [comment]
Great job! Please refer to the Pull Request on your project repo for feedback: 
https://github.com/TimGafvert/Towers-Of-Hanoi/pull/1
👍
