### ISSUE TITLE
Project 1 - Trivia Game - Liz Jewell

### ISSUE THREAD

**Issue by lizardbird** [ga-dc/project1-gallery#182]
Link to repo: https://github.com/lizardbird/wdi-proj1-trivia
Link to deployed app: https://lizardbird.github.io/wdi-proj1-trivia/

Things you'd like specific feedback on: I can't tell if my GitHub pages is still loading or if the images are broken, but they are not showing up on my GitHub pages version and the console is listing a 404 () file not found. Wahhh! :(

**Comment by lizardbird** [comment]
Update - got it to work. Turns out that Git Hub pages is case sensitive for both folder and file names. On each image reference, I listed a relative path of "images/x.jpg" vs "Images/x.jpg" as my folder was named. I edited the references in HTML and CSS and now the page is loading properly.

**Comment by AndyWhitley** [comment]
Great job! Please refer to the Pull Request on your project repo for feedback: 
https://github.com/lizardbird/wdi-proj1-trivia/pull/7
👍
