### ISSUE TITLE
Jacob Greenwald Simon Says

### ISSUE THREAD

**Issue by jacobg1** [ga-dc/project1-gallery#183]
Link to deployed app: https://jacobg1.github.io/Simon-Says/

Link to repo: https://github.com/jacobg1/Simon-Says

Things you'd like specific feedback on:

how to stop sequence so that if user gets a wrong choice it doesn't fire the simon pattern.  right now it finishes the sequence, doesn't break the game but is annoying for the user

**Comment by juancgarcia** [comment]
Great job! Please refer to the Pull Request on your project repo for feedback: 
https://github.com/jacobg1/Simon-Says/pull/8
👍
