### ISSUE TITLE
Jessica Marie - Hangman

### ISSUE THREAD

**Issue by jessamarie** [ga-dc/project1-gallery#184]
Link to repo: https://github.com/jessamarie/hangman
Link to deployed app: https://jessamarie.github.io/hangman/

Things you'd like specific feedback on:
- Model-VIew set up. Is there anything that I can move to the model? Could I have created another class to minimize code bloat?
- Handling of event listeners in the view. Can I make this more DRY somehow? Instead of having so many functions for different versions of the game

**Comment by juancgarcia** [comment]
Great job! Please refer to the Pull Request on your project repo for feedback: 
https://github.com/jessamarie/hangman/pull/1
👍
