### ISSUE TITLE
Matt Filbert - SimonBoy COLOR

### ISSUE THREAD

**Issue by mattcfilbert** [ga-dc/project1-gallery#185]
Link to repo: https://github.com/mattcfilbert/SimonBoy-Color
Link to deployed app: https://mattcfilbert.github.io/SimonBoy-Color/

Things you'd like specific feedback on: 

I would like to receive criticism on how clean, tight, and organized my code is. I believe it is currently in need of improvement, especially as we move to more complicated programming.

**Comment by AndyWhitley** [comment]
Great job on this project. Please refer to the Pull Request on your project's repo for feedback:
https://github.com/mattcfilbert/SimonBoy-Color/pull/1

👍
