### ISSUE TITLE
Towers_of_Hanoi(Josue Rosales)

### ISSUE THREAD

**Issue by jhosuedeveloper** [ga-dc/project1-gallery#190]
Link to repo: https://github.com/jhosuedeveloper/Towers_of_Hanoi
Link to deployed app: https://jhosuedeveloper.github.io/Towers_of_Hanoi/

**Comment by AndyWhitley** [comment]
Please refer to the Pull Request on the project's repo for feedback:
https://github.com/jhosuedeveloper/Towers_of_Hanoi/pull/1

👍
