### ISSUE TITLE
Project1-Hangman-Diona

### ISSUE THREAD

**Issue by dionadk** [ga-dc/project1-gallery#194]
Link to repo: https://github.com/dionadk/Project1
Link to deployed app: https://dionadk.github.io/Project1/

Things you'd like specific feedback on:
I would like to get a feed back on how my js coding is and how much more can i refactor the code.
Also if its easy for everyone to read. had a tough time adding meaningful id class and variables.

**Comment by aspittel** [comment]
Good job! See https://github.com/dionadk/Project1/pull/1
