### ISSUE TITLE
Concentration Game

### ISSUE THREAD

**Issue by chapel-of-bools** [ga-dc/project1-gallery#2]
Link to repo: https://github.com/mrscott90/Concentration
Link to deployed app: http://mrscott90.github.io/Concentration/

Things you'd like specific feedback on:
I feel like my javacript could be more DRY and written more efficiently, any help with this would be greatly appreciated.

**Comment by RobertAKARobin** [comment]
# Project Feedback + Evaluation

| Score | Expectations |
| --- | --- |
| 0 | Incomplete |
| 1 | Progressing |
| 2 | Performing |
| 3 | Excelling |

## Project Workflow: 1

> Did you complete the user stories, wireframes, task tracking, and/or ERDs, as specified above? Did you use source control as expected for the phase of the program you’re in?

## Technical Requirements: 2

> Did you deliver a project that met all the technical requirements? Given what the class has covered so far, did you build something that was reasonably complex?

## Code Quality: 2

> Did you follow code style guidance and best practices covered, such as spacing, modularity, and semantic naming? Did you comment your code?

## Creativity/Interface: 3

> Is your user interface easy to use and understand? Does it make sense for the problem you're solving? Does your interface demonstrate creative design?

## Overall: 2

See my inline comments here: https://github.com/mrscott90/Concentration/pull/2/files

Please write out your bronze/silver/gold next time.

Nice job, Matt!

Honestly, I think your JS is pretty dry already. Only thing I might suggest is taking the stuff inside your `if/else` blocks and extracting it into functions. This keeps the `if/else` easier to read.

I did notice your code is rather similar to Gandy's:

https://github.com/gandyland/github.io-Concentration_Memory/blob/master/script.js

Nothing wrong with using a tutorial, but it does make it harder for me to leave helpful comments on your code. Next time, I'd recommend reading through the tutorial's code, translating their code into pseudocode, closing the tutorial, and re-creating the code from the pseudocode.

**Comment by RobertAKARobin** [comment]
https://www.developphp.com/video/JavaScript/Memory-Game-Programming-Tutorial
