### ISSUE TITLE
Stella Gordon-Zigel Trivia Game

### ISSUE THREAD

**Issue by stellagordonzigel** [ga-dc/project1-gallery#208]
Link to repo: https://github.com/stellagordonzigel/trivia_game/tree/gh-pages
Link to deployed app: https://stellagordonzigel.github.io/trivia_game/

Things you'd like specific feedback on: format of my script.js file

**Comment by perryf** [comment]
Please refer to the Pull Request on your project repo for feedback:
https://github.com/stellagordonzigel/trivia_game/pull/1
