### ISSUE TITLE
Meg MacIver Project 1

### ISSUE THREAD

**Issue by megmaciver13** [ga-dc/project1-gallery#209]
Link to repo: https://github.com/megmaciver13/game-on-gluten
Link to deployed app: https://megmaciver13.github.io/game-on-gluten/

Things you'd like specific feedback on: lines 31-37 (I couldn't get the for loop to work - it seemed like the final '.letter' in the last variable on line 36 was the problem), tips for improving user experience (too many clicks?, alignment of questions/answers)

**Comment by AndyWhitley** [comment]
Great job on this project 👍 please refer to the Pull Request on your project repo for feedback:
https://github.com/megmaciver13/game-on-gluten/pull/2
