### ISSUE TITLE
Project 01 (Simon) -- Sarah Yu

### ISSUE THREAD

**Issue by sarah-yu** [ga-dc/project1-gallery#210]
Link to repo: https://github.com/sarah-yu/simon
Link to deployed app: https://sarah-yu.github.io/simon

Things you'd like specific feedback on:
My logic is messy and convoluted and I don't think I did a good job keeping my code DRY... I probably should not have tried to get creative with this project because while the idea sounded good in my head, the execution of it was more complicated than I had anticipated.
I also could not resolve some issues with flexbox, and there is a small error with clearTimeout if you click the "start page" button before playing any of the levels.

**Comment by perryf** [comment]
Please refer to the Pull Request on your project repo for feedback:
https://github.com/sarah-yu/simon/pull/1
