### ISSUE TITLE
Project 1 Steven Connors

### ISSUE THREAD

**Issue by StevenC53** [ga-dc/project1-gallery#211]
Link to repo: https://github.com/StevenC53/Trivia-Game
Link to deployed app: https://stevenc53.github.io/Trivia-Game/

Things you'd like specific feedback on: Length and Functionality of Functions

**Comment by perryf** [comment]
Please refer to the Pull Request on your project repo for feedback:
https://github.com/StevenC53/Trivia-Game/pull/2
