### ISSUE TITLE
Trivia Game - Angie Spears

### ISSUE THREAD

**Issue by AMSpears** [ga-dc/project1-gallery#212]
Link to repo: https://github.com/AMSpears/Trivia/tree/gh-pages
Link to deployed app: https://amspears.github.io/Trivia/

Things you'd like specific feedback on:
Please take a look at the future implementations under the readme description and let me know if you have any suggestions. I appreciate any other feedback.

**Comment by perryf** [comment]
Please refer to the Pull Request on your project repo for feedback:
https://github.com/AMSpears/Trivia/pull/1
