### ISSUE TITLE
Casey Jordan Simon Project 1

### ISSUE THREAD

**Issue by caseymjordan11** [ga-dc/project1-gallery#213]
repo link: https://github.com/caseymjordan11/project1
working game link: https://caseymjordan11.github.io/project1/

Comments: 

Game and functionality work great and as I wanted them to. Just now realizing that when styling the game I made it so it looked great in my computer's browser window, but when resized it squishes and things pile onto one another. This also happens if opening in a window on a computer with a different sized screen than mine. Trying to resolve by the time presentations happen. 

However, if you can see the full game and have it spaced out on your screen the whole thing works perfectly.

**Comment by AndyWhitley** [comment]
Great job on this project 👍 please see the Pull Request on your project repo for feedback: 
https://github.com/caseymjordan11/project1/pull/1
