### ISSUE TITLE
Declan Kurant Project 1 Hangman

### ISSUE THREAD

**Issue by Declan-Kurant** [ga-dc/project1-gallery#214]
Link to repo:               https://github.com/Declan-Kurant/Project-1-Hangman
Link to deployed app:        https://declan-kurant.github.io/Project-1-Hangman/

Things you'd like specific feedback on: 
re CSS : hangman gets deformed when page is resized--how to resolve?
re JS : In parts of my code (53-55) I call the function, bodyPartsAdd(), and then an alert on the next line; however the alert pops up for the user before the function is able to load the next body part. I wasn't sure how to prevent this.
re HTML : I'm not sure if my use of id's and classes was in accordance with best practices--what would be a good way to rectify this?

**Comment by perryf** [comment]
Please refer to the Pull Request on your project repo for feedback:
https://github.com/Declan-Kurant/Project-1-Hangman/pull/1
