### ISSUE TITLE
Jack Tyburski (Hangman) Project 1

### ISSUE THREAD

**Issue by Simplejack17** [ga-dc/project1-gallery#215]
Link to repo: https://github.com/Simplejack17/Hangman-Game
Link to deployed app: https://simplejack17.github.io/Hangman-Game/

Things you'd like specific feedback on:
- Aside from the comments, is the code set up in a organized fashion? 
- Was there an easier way to accomplish this?
- Do I have any unnecessary code?

**Comment by AndyWhitley** [comment]
Please refer to the Pull Request on your project repo for feedback:
https://github.com/Simplejack17/Hangman-Game/pull/1
