### ISSUE TITLE
Dan McQuade  - Project 1

### ISSUE THREAD

**Issue by danmcquade** [ga-dc/project1-gallery#216]
Link to repo: https://github.com/danmcquade/js-simon
Link to deployed app: https://danmcquade.github.io/js-simon/

Things you'd like specific feedback on: I'd like to learn where my code can be cleaned up and made more efficient. For instance, I know that the checkSolution() function can be streamlined and cleaned up a bit. I'd also like to make the game responsive (currently the game board is a fixed size, and doesn't properly scale depending on resolution).

**Comment by 0xZakk** [comment]
Hey Dan, great job! You can see all my feedback [here](https://github.com/ZakkMan/js-simon/blob/master/feedback.md)
