### ISSUE TITLE
Troy Sipprelle Tower of Hanoi

### ISSUE THREAD

**Issue by troysipp** [ga-dc/project1-gallery#219]
Link to repo:
https://github.com/troysipp/tower-of-hanoi
Link to deployed app:
https://troysipp.github.io/tower-of-hanoi/

Things you'd like specific feedback on:
Everything!  The code and the design?
Mostly my next step would be to clean up the code so that I only have one event listener function that works for each pole.  Then I could add functionality that would enable you to change the number of discs you could play with.

**Comment by AndyWhitley** [comment]
Great work 👍 Please refer to the pull request on your project repo for feedback: https://github.com/troysipp/tower-of-hanoi/pull/1
