### ISSUE TITLE
Farris Ismati Hangman

### ISSUE THREAD

**Issue by FarrisIsmati** [ga-dc/project1-gallery#221]
Link to repo: https://github.com/FarrisIsmati/farris-hangman
Link to deployed app: https://farrisismati.github.io/farris-hangman/

Things you'd like specific feedback on: Look over how I said I would like to reorganize my code (In the readme) and see if that's a much better approach. I didn't like how oversaturated my GameView class is.

**Comment by AndyWhitley** [comment]
Great job on this project 👍 Please see the Pull Request on your project repo for feedback:
https://github.com/FarrisIsmati/farris-hangman/pull/1
