### ISSUE TITLE
Simon (Sloan-Holzman)

### ISSUE THREAD

**Issue by sloan-holzman** [ga-dc/project1-gallery#222]
Link to repo: https://github.com/sloan-holzman/simon/tree/gh-pages
Link to deployed app: https://sloan-holzman.github.io/simon/

Things you'd like specific feedback on: am I following best practices?  are there ways to make it faster?  where can I refactor to make faster?  Also, am I attacking the mobile optimization correctly?  For example, why doesn't it center automatically when I switch to mobile?

**Comment by 0xZakk** [comment]
Hey Sloan,

Great job on your project! You can find my feedback [here](https://github.com/sloan-holzman/simon/pull/1)
