### ISSUE TITLE
Ante Bozic Tower of Hanoi

### ISSUE THREAD

**Issue by antebozic** [ga-dc/project1-gallery#224]
Link to repo: https://github.com/antebozic/Tower-of-Hanoi
Link to deployed app: https://antebozic.github.io/Tower-of-Hanoi/index.html
Things you'd like specific feedback on: how to make code more simple and if I'm violating some common practices in my code

**Comment by 0xZakk** [comment]
Hey Ante, you can find my feedback [here](https://github.com/antebozic/Tower-of-Hanoi/pull/1)

Great job on the project!
