### ISSUE TITLE
WDI19-Project-1-JaredTaylor

### ISSUE THREAD

**Issue by taylorJaredD** [ga-dc/project1-gallery#225]
Link to repo: https://github.com/taylorJaredD/tower_of_hanoi
Link to deployed app: https://taylorjaredd.github.io/tower_of_hanoi/

Things you'd like specific feedback on: I know the project isn't complete but I learned a lot this week and plan on continuing to work on the project and have a working version.

**Comment by 0xZakk** [comment]
Hey Jared,

You did a good job with what you have and I can see you learned a lot. Unfortunately, there isn't enough completed functionality for me to mark this project as complete.

What that means is that, for now, you'll have an incomplete in Garnet for Project 1. You'll have until Monday January 8th, 2018 (the first Monday of Project 4) to complete the project. That said, I strongly recommend finishing it sooner. You can come to office hours and ask questions about the project, reach out to me on slack with any questions or set up a time for us to meet in person and go over any questions you have.

I want to reiterate again that I think you have what it takes to complete the project and do a great job on it.

Let me know if you have any questions.

Thanks,
Zakk
