### ISSUE TITLE
Zach Bauer - Tower of Hanoi

### ISSUE THREAD

**Issue by WrylyRiley** [ga-dc/project1-gallery#228]
Link to repo: [Repo](https://github.com/zbauer91/Tower-of-Hanoi/tree/gh-pages)
Link to deployed app: [Game](https://zbauer91.github.io/Tower-of-Hanoi/)

Things you'd like specific feedback on: [The CSS Validator](https://jigsaw.w3.org/css-validator/validator?uri=https%3A%2F%2Fzbauer91.github.io%2FTower-of-Hanoi%2F&profile=css3&usermedium=all&warning=1&vextwarning=&lang=en
) indicates three of my properties are not valid CSS, however they're just very new. Both properties are drafted in the CSS specification [here](https://developer.mozilla.org/en-US/docs/Web/CSS/justify-self) and [here](https://developer.mozilla.org/en-US/docs/Web/CSS/align-self). I wasn't sure what else to use other than defining a new flexbox and using that, so I left it all in there.

**Comment by aspittel** [comment]
🔥 Great job! Feedback: https://github.com/zbauer91/Tower-of-Hanoi/pull/3/files
