### ISSUE TITLE
Gwen Latasa-Proj1-Simon

### ISSUE THREAD

**Issue by gxlgit** [ga-dc/project1-gallery#231]
[Repo](https://github.com/gxlgit/simon_game)
[Game](https://gxlgit.github.io/simon_game/)

Still trying to figure out that sticky header!  
I know that I can go back and make the code a little more DRY.

**Comment by aspittel** [comment]
🎉  awesome job Gwen! Feeback here: https://github.com/gxlgit/simon_game/pull/1
