### ISSUE TITLE
Hammad Malik Submission: Simon

### ISSUE THREAD

**Issue by tomatohammado** [ga-dc/project1-gallery#234]
Link to repo: https://github.com/tomatohammado/simon
Link to deployed app: https://tomatohammado.github.io/simon/

---
I still get an error and warning from the [W3 Css Validator](https://jigsaw.w3.org/css-validator/)
- `Property pointer-events doesn't exist : none`

I checked the [MDN page for pointer events](https://developer.mozilla.org/en-US/docs/Web/CSS/pointer-events) and it looks totally valid, not sure why I'm getting the error

- `Imported style sheets are not checked in direct input and file upload modes`

I imported my fonts to the stylesheet, and got a warning about it. It isn't enough of a reason for me to add fonts to the HTML (which causes another kind of error, but that's a different story)

---
My commit for the presentations is `d5287ef`

I thought it was bugged, but it seems to work just fine. Couldn't replicate the issue I saw when I tried  what I deployed to Github pages.

I made a second commit `8bbd731` to quickly incorporate some of the feedback I got during the presentations, and to clean up some of the corrections I made last minute based on the W3 validation results.

**Comment by aspittel** [comment]
🎉  Awesome job! Feeback here: https://github.com/tomatohammado/simon/pull/1
