### ISSUE TITLE
Alonzo-Animal_Trivia_Game

### ISSUE THREAD

**Issue by developedbyzo** [ga-dc/project1-gallery#237]
Link to repo: https://github.com/mosesa0609/Animal-Trivia
Link to deployed app: https://mosesa0609.github.io/Animal-Trivia/

Things you'd like specific feedback on: How could I have designed the button so it would not accept any further submission?

**Comment by aspittel** [comment]
Great job 🎉! Full feedback: https://github.com/mosesa0609/Animal-Trivia/pull/1/files
