### ISSUE TITLE
Tyler Rosenberg - Project 1

### ISSUE THREAD

**Issue by TyRyanR** [ga-dc/project1-gallery#24]
Link to repo: https://github.com/TyRyanR/Project_1
Link to deployed app: https://tyryanr.github.io/Project_1/

Not 100% clear on why the LIGHT IN and LIGHT OUT functions had to be created on line 93 and 102. Originally I had tried to put the setTimeout in the for loop of the ITERATOR function, however, for some reason maybe having to do with the call stack, my program only worked if I CALLED the LIGHT IN / LIGHT OUT functions from within the for loop. Both light in and light out then contain a setTimeout inside. If however, I tried to simply put the setTimeout inside the for loop, it wouldn't work. 

I believe this has to do with passing through a new delay value, created in the ITERATOR function, for each time the setTimeout is called.

**Comment by nayana487** [comment]
Total: 12/12

Project Workflow: 3/3 - Excellent job here! You user stories are succinct but clear and your methodology is well-documented. It'd be helpful though to include a general statement at the top of your readme explaining high-level what the project is. Your wireframe is also a great start to the initial brainstorming process, but in the future, I'd encourage you to try making a few versions and experimenting with some wireframing software: https://balsamiq.com/.

Technical Requirements: 3/3 - You made your own plugin, very cool! You've definitely gone above and beyond what we could've expected. Also cool that you implemented timer functions, which is very challenging to do. I think the issues you're having involve the asynchronous nature of timer functions. This article does a pretty good job of explaining: http://ejohn.org/blog/how-javascript-timers-work/

Code Quality: 3/3 - Your code is organized and spaced beautifully. I also love that you included lots of comments and pseudocode--that made it really easy to understand what is happening in your app. My one thought for improvement here would be that you organize your files into folders--that is, put normalize and your custom stylesheet in a CSS folder, your plugin and script in a JS folder and your wireframe in a planning folder. 

Creativity: 3/3 - The app design is lovely and you clearly put a lot of thought into the user interface and general user experience.
