### ISSUE TITLE
Temicka Project1/Trivia

### ISSUE THREAD

**Issue by temickab** [ga-dc/project1-gallery#241]
Link to repo: https://github.com/temickab/project1-Trivia
Link to deployed app: https://temickab.github.io/project1-Trivia/

Things you'd like specific feedback on:

Advice on keeping JS DRY

**Comment by ghost** [comment]
Good work! 
You can make the JS code more DRY by combining the 5 checkAnswer functions in one. It should look similar to this (but not exactly)

```js
function checkAnswer(){
  if(this.previousElementSibling.value === answers[this.id]){
      score ++  
      alert('YAY CORRECT')
  }
  else{
      alert('Wrong! Try Again!')
  }
}
```
