### ISSUE TITLE
Marquet's Simon Game

### ISSUE THREAD

**Issue by quetcodesfire** [ga-dc/project1-gallery#249]
[Deployed Game](https://codenamequet.github.io/simon/)
[Repo](https://github.com/codenamequet/simon)

**Comment by comrade-kirby** [comment]
Your completed project looks great! Simon is a difficult game to reproduce and you pulled it together nicely. Your code looks good; it's indented consistently, semantic, and not too repetitive.
Very good work!

Deployment: 3
Technical Requirements: 3
Code Quality: 3
- code is organized consistently
- pretty DRY!
Creativity/Interface: 2
- simple and effective design

Score | Expectations
0 | Incomplete
1 | Progressing
2 | Performing
3 | Excelling
