### ISSUE TITLE
John Estes - Project 1

### ISSUE THREAD

**Issue by johnestes4** [ga-dc/project1-gallery#25]
Link to repo: https://github.com/johnestes4/project1
Link to deployed app: https://johnestes4.github.io/project1/

Things you'd like specific feedback on: The general styling of the page, and any suggestions for a problem I never figured out how to fix with the colors overlapping the border.

**Comment by andrewsunglaekim** [comment]
Great job on project 1 john! Check the PR I made on your repo for comments and rubric, let me know if you have any questions 👍
