### ISSUE TITLE
Project 1 (Angela Malone)

### ISSUE THREAD

**Issue by angmalone** [ga-dc/project1-gallery#254]
Link to repo: https://github.com/angmalone/project-1
Link to deployed app: https://angmalone.github.io/project-1/

Things you'd like specific feedback on:
Really want to know if I wrote just the right amount of Javascript or if I made it more complicated than it needs to be!

**Comment by perryf** [comment]
👍 Great work on the project.  
Feedback can be found in my pull request
https://github.com/angmalone/project-1/pull/1
