### ISSUE TITLE
Project 1 (Jeffrey Heller)

### ISSUE THREAD

**Issue by Jheller11** [ga-dc/project1-gallery#255]
Link to repo: https://github.com/Jheller11/pyramids
Link to deployed app: https://jheller11.github.io/pyramids/

Things you'd like specific feedback on:
The game is controlled by pushing and splicing block objects from arrays located in each column object.  Each time a "move" is made, the arrays update and the columns remove all of the pyramid levels currently displayed and recreate all of them based on the new contents of each columns array.  Is this ok or should I have instead tried to just actually move the elements around the page?  Also, I refactored once but I think there are probably still ways to simplify the code.  If anythings stands out as particularly repetitive or maybe unnecessary please let me know.  Thanks!

**Comment by perryf** [comment]
👍 Please refer to my pull request to see feedback (https://github.com/Jheller11/pyramids/pull/2)

I would say the way you did it is really the recommended way to do it.  I actually think its easier just to read the elements on the page and move them around, but keeping track of them as arrays in your js is a better way to do it and ensures more control over your data. Great work!
