### ISSUE TITLE
Simon Says 

### ISSUE THREAD

**Issue by aytam-wu** [ga-dc/project1-gallery#258]
**Link to repo:** 
https://github.com/aiyentam/Simon-Says

**Link to deployed app:** 
https://aiyentam.github.io/Simon-Says/

**Things you'd like specific feedback on:** 
Everything please!

**Comment by 0xZakk** [comment]
# Project Feedback + Evaluation

| Score | Expectations |
|   --- | ---          |
|     0 | Incomplete   |
|     1 | Progressing  |
|     2 | Performing   |
|     3 | Excelling    |

## Deployment:

> Did you successfully deploy your project to github pages? Is the app's functionality the same deployed as it is locally?

**Your Score: 2**

It's great to see your project deployed to GitHub Pages!

## Technical Requirements:

> Did you deliver a project that met all the technical requirements? Given what the class has covered so far, did you build something that was reasonably complex?

**Your Score: 2**

Your project looks really great and your game functions really smoothly! It looks like you worked really hard on it!

## Code Quality:

> Did you follow code style guidance and best practices covered in class, such as spacing, modularity, and semantic naming? Did you comment your code?

**Your Score: 2**

Your HTML and CSS are well written and semantic. Your JS shows that you worked hard on it and spent a lot of time thinking through the problem. Overall, your code is clean and well organized! 

## Creativity/Interface:

> Is your user interface easy to use and understand? Does it make sense for the problem you're solving? Does your interface demonstrate creative design?

**Your Score: 2**

The interface is great - I really like the way you got the buttons to fade in and out and work with your timer.
