### ISSUE TITLE
Daniel Freudberg's Trivia!

### ISSUE THREAD

**Issue by dbf8** [ga-dc/project1-gallery#260]
Link to repo: https://github.com/dbf8/Trivia-Game
Link to deployed app: https://dbf8.github.io/Trivia-Game/

Things you'd like specific feedback on:  better ways to do my scoring. It's pretty jury-rigged.

Woo!

**Comment by perryf** [comment]
👍 Woo!  
Please refer to the pull request for project feedback. 
https://github.com/dbf8/Trivia-Game/pull/1
