### ISSUE TITLE
Spanish Trivia

### ISSUE THREAD

**Issue by HannahAurand** [ga-dc/project1-gallery#261]
Link to repo: https://github.com/HannahAurand/SpanishTrivia
Link to deployed app: hannahaurand.github.io/SpanishTrivia

Things you'd like specific feedback on: How I could have done this with less code, or made it more streamlined. Logical ways to approach the issues I faced that would have made it faster/more efficient programming. And also, why won't google font work on github pages?

**Comment by 0xZakk** [comment]
# Project Feedback + Evaluation

| Score | Expectations |
|   --- | ---          |
|     0 | Incomplete   |
|     1 | Progressing  |
|     2 | Performing   |
|     3 | Excelling    |

## Deployment:

> Did you successfully deploy your project to github pages? Is the app's functionality the same deployed as it is locally?

**Your Score: 2**

It's great to see your project deployed to GitHub Pages!

## Technical Requirements:

> Did you deliver a project that met all the technical requirements? Given what the class has covered so far, did you build something that was reasonably complex?

**Your Score: 2**

Your project looks really great! It looks like you worked really hard on it!

## Code Quality:

> Did you follow code style guidance and best practices covered in class, such as spacing, modularity, and semantic naming? Did you comment your code?

**Your Score: 2**

Your code is well organized and modular. It looks like you worked really hard on it! Your CSS is especially great and the site is well designed.

## Creativity/Interface:

> Is your user interface easy to use and understand? Does it make sense for the problem you're solving? Does your interface demonstrate creative design?

**Your Score: 3**

I love the interface!
