### ISSUE TITLE
Project 1: Flash-Card_Game (Hyojin Sarchet)

### ISSUE THREAD

**Issue by hyojinsarchet** [ga-dc/project1-gallery#262]
Link to repo: https://github.com/hyojinsarchet/Flash-Card-Game
Link to deployed app: https://hyojinsarchet.github.io/Flash-Card-Game

Things you'd like specific feedback on:
I'd appreciate any opinion about my project. Also let me know if you have better ideas to make this project better/upgraded.

**Comment by 0xZakk** [comment]
# Project Feedback + Evaluation

| Score | Expectations |
|   --- | ---          |
|     0 | Incomplete   |
|     1 | Progressing  |
|     2 | Performing   |
|     3 | Excelling    |

## Deployment:

> Did you successfully deploy your project to github pages? Is the app's functionality the same deployed as it is locally?

**Your Score: 2**

It's great to see your project deployed to GitHub Pages!

## Technical Requirements:

> Did you deliver a project that met all the technical requirements? Given what the class has covered so far, did you build something that was reasonably complex?

**Your Score: 2**

Your project looks really great, like you worked really hard on it!

## Code Quality:

> Did you follow code style guidance and best practices covered in class, such as spacing, modularity, and semantic naming? Did you comment your code?

**Your Score: 2**

Your code is well organized and generally pretty semantic. You did a great job and must have worked hard!

## Creativity/Interface:

> Is your user interface easy to use and understand? Does it make sense for the problem you're solving? Does your interface demonstrate creative design?

**Your Score: 2**

Your interface looks very neat and well designed!
