### ISSUE TITLE
Mahwish's Trivia 

### ISSUE THREAD

**Issue by ghost** [ga-dc/project1-gallery#264]
Link to repo: https://github.com/Mavz2013/Trivia_project_1/tree/gh-pages
Link to deployed app: https://mavz2013.github.io/Trivia_project_1/

Things you'd like specific feedback on: how to add media query.

**Comment by perryf** [comment]
👍 
Please refer to the pull request for project feedback. 
https://github.com/Mavz2013/Trivia_project_1/pull/1
