### ISSUE TITLE
Tower of Hanoi (Nhi Nguyen)

### ISSUE THREAD

**Issue by nnguy152** [ga-dc/project1-gallery#265]
Link to Repo: https://github.com/nnguy152/01-Tower-of-Hanoi
Link to Deployed App: https://nnguy152.github.io/01-Tower-of-Hanoi/

Things You'd Like Specific Feedback On: 
1) For my modes, if I click on the next mode and try to go back to the original mode, it won't change. So maybe like whether it's because of the code or if it's better to make new HTML pages for each mode.
2) Tips of refactoring to shorten the length/make it more efficient.

**Comment by 0xZakk** [comment]
# Project Feedback + Evaluation

| Score | Expectations |
|   --- | ---          |
|     0 | Incomplete   |
|     1 | Progressing  |
|     2 | Performing   |
|     3 | Excelling    |

## Deployment:

> Did you successfully deploy your project to github pages? Is the app's functionality the same deployed as it is locally?

**Your Score: 2**

It's great to see your project deployed to GitHub Pages!

## Technical Requirements:

> Did you deliver a project that met all the technical requirements? Given what the class has covered so far, did you build something that was reasonably complex?

**Your Score: 3**

You definitely met the technical requirements - I love all the additional flare you added!

## Code Quality:

> Did you follow code style guidance and best practices covered in class, such as spacing, modularity, and semantic naming? Did you comment your code?

**Your Score: 2**

Your code is well organized and generally pretty semantic. You did a great job and must have worked hard!

## Creativity/Interface:

> Is your user interface easy to use and understand? Does it make sense for the problem you're solving? Does your interface demonstrate creative design?

**Your Score: 3**

Your game is very creative! Really great work on the bonus modes!
