### ISSUE TITLE
Project One Trivia (Samuel Haile)

### ISSUE THREAD

**Issue by samishken** [ga-dc/project1-gallery#267]
Link to repo:  https://github.com/samishken/Trivia-Game-
Link to deployed app: https://samishken.github.io/Trivia-Game-/

Things you'd like specific feedback on:
Planning
Checking bugs

**Comment by perryf** [comment]
Great work!
Please refer to my pull request for project feedback
https://github.com/samishken/Trivia-Game-/pull/1
