### ISSUE TITLE
Qya A. Project 1

### ISSUE THREAD

**Issue by rahmad239** [ga-dc/project1-gallery#268]
Link to repo: https://github.com/rahmad239/GA-Projects-/tree/gh-pages/project_1
Link to deployed app: https://rahmad239.github.io/GA-Projects-/project_1/

Things you'd like specific feedback on:
Loops! How could I have avoided ALLLLLLL of these lines.

**Comment by 0xZakk** [comment]
# Project Feedback + Evaluation

| Score | Expectations |
|   --- | ---          |
|     0 | Incomplete   |
|     1 | Progressing  |
|     2 | Performing   |
|     3 | Excelling    |

## Deployment:

> Did you successfully deploy your project to github pages? Is the app's functionality the same deployed as it is locally?

**Your Score: 1**

It's great to see your project deployed to GitHub Pages! You currently seem to have 1 repository with 2 projects in it and an old version of one of those projects. To bring this to a 2, you'd need have cleaned that up so you have just 1 repository per project.

## Technical Requirements:

> Did you deliver a project that met all the technical requirements? Given what the class has covered so far, did you build something that was reasonably complex?

**Your Score: 1**

It looks like you worked really hard on this project and you were able to write a lot of code! The next step for you is to start thinking about accomplishing the same goal with less code - significantly less code! Now that you have a good grasp on the basics of working with objects and arrays and working with DOM nodes and event listeners, try to start thinking about how to write less code that solves the same problem!

## Code Quality:

> Did you follow code style guidance and best practices covered in class, such as spacing, modularity, and semantic naming? Did you comment your code?

**Your Score: 1**

It's great to see you working hard and getting it working in a week! Your next challenge is to use more semantic HTML elements and be more modular/dynamic in your code!

## Creativity/Interface:

> Is your user interface easy to use and understand? Does it make sense for the problem you're solving? Does your interface demonstrate creative design?

**Your Score: 2**

It looks great!
