### ISSUE TITLE
Grant Brown Project 1

### ISSUE THREAD

**Issue by grantnathanielbrown** [ga-dc/project1-gallery#269]
Link to repo: https://github.com/grantnathanielbrown/wdi-project-one
Link to deployed app: https://grantnathanielbrown.github.io/wdi-project-one/

Sorry, I forgot to submit this as an issue earlier.

Things you'd like specific feedback on:

**Comment by 0xZakk** [comment]
# Project Feedback + Evaluation

| Score | Expectations |
|   --- | ---          |
|     0 | Incomplete   |
|     1 | Progressing  |
|     2 | Performing   |
|     3 | Excelling    |

## Deployment:

> Did you successfully deploy your project to github pages? Is the app's functionality the same deployed as it is locally?

**Your Score: 2**

Really great work! It looks like you only have a `gh-pages` branch? You want to have a `master` branch and a `gh-pages` branch. All your work can be on `master` and then when you're ready to deploy your work, you can merge it into `gh-pages` and push.

## Technical Requirements:

> Did you deliver a project that met all the technical requirements? Given what the class has covered so far, did you build something that was reasonably complex?

**Your Score: 2**

Everything looks great!

## Code Quality:

> Did you follow code style guidance and best practices covered in class, such as spacing, modularity, and semantic naming? Did you comment your code?

**Your Score: 2**

## Creativity/Interface:

> Is your user interface easy to use and understand? Does it make sense for the problem you're solving? Does your interface demonstrate creative design?

**Your Score: 2**
