### ISSUE TITLE
project 1 

### ISSUE THREAD

**Issue by BonnieHilliard** [ga-dc/project1-gallery#270]
[Hangman 2.zip](https://github.com/ga-dc/project1-gallery/files/1763265/Hangman.2.zip)

**Comment by BonnieHilliard** [comment]
web link:  https://git.generalassemb.ly/pages/Bonnie/Hangman/
 repo:  https://git.generalassemb.ly/Bonnie/Hangman

**Comment by perryf** [comment]
👍 Good job Bonnie.  You almost have it all working
Please see my pull request to see feedback on the project.
https://git.generalassemb.ly/Bonnie/Hangman/pull/1
