### ISSUE TITLE
Completed Project 1: Hangman

### ISSUE THREAD

**Issue by petey284** [ga-dc/project1-gallery#273]
Link to repo: https://github.com/petey284/hangman/tree/gh-pages
Link to deployed app: http://petey284.github.io/hangman/

Things you'd like specific feedback on:
So I can see the page building in the background whenever I refresh. Is there a way to limit this when a user enters the webpage.

**Comment by aspittel** [comment]
Awesome Job!! Full feedback! https://github.com/petey284/hangman/pull/1/files
