### ISSUE TITLE
Flash Cards Project 1

### ISSUE THREAD

**Issue by kebedemeron905** [ga-dc/project1-gallery#275]
Link to repo: https://github.com/kebedemeron905/Project-One
Link to deployed app: https://kebedemeron905.github.io/Project-One/

Things you'd like specific feedback on:

- suggestions on how I could have made my code DRYer.
-  class naming conventions

Thank you!
Meron

**Comment by aspittel** [comment]
Awesome job 🎉! Feedback: https://github.com/kebedemeron905/Project-One/pull/1
