### ISSUE TITLE
Project 1 Self-scoring Trivia Game

### ISSUE THREAD

**Issue by MQThai** [ga-dc/project1-gallery#277]
Link to repo: https://git.generalassemb.ly/MQThai/Self-scoring-Trivia-Project1
Link to deployed app: https://git.generalassemb.ly/pages/MQThai/Self-scoring-Trivia-Project1/

Feedback -
- If code is DRY enough
- if there is a cleaner/easier way of setting up my questions and answers

**Comment by aspittel** [comment]
👍 awesome job! Full feedback: https://git.generalassemb.ly/MQThai/Self-scoring-Trivia-Project1/pull/1
