### ISSUE TITLE
Megan's Flash Cards

### ISSUE THREAD

**Issue by megancoyle** [ga-dc/project1-gallery#28]
Link to repo: https://github.com/megancoyle/flash-cards
Link to deployed app: https://megancoyle.github.io/flash-cards/

Things you'd like specific feedback on:
If I'm doing anything that isn't really best practices for this ^_^ quite honestly, any feedback about how I structure things or even if you think there's a different way I might want to think about things would be really helpful.

Also, I attempted to work on hangman too. Still a work in progress though:
repo: https://github.com/megancoyle/hangman
app: https://megancoyle.github.io/hangman/

**Comment by andrewsunglaekim** [comment]
Great work! Refer to PR for comments/rubric 👍
