### ISSUE TITLE
Daniel Lousa Project 1

### ISSUE THREAD

**Issue by dlousa92** [ga-dc/project1-gallery#285]
Link to repo: https://github.com/dlousa92/triviagame
Link to deployed app: https://dlousa92.github.io/triviagame/

Things you'd like specific feedback on: Efficiency of javascript code / Ways to make it more efficient

**Comment by dlousa92** [comment]
How dare you

**Comment by jabyess** [comment]
LOL! sorry dude. time must move forward. hope you're doin well.

**Comment by dlousa92** [comment]
Doing great! Working in DC now at CSIS
