### ISSUE TITLE
Jac-Ahn-Project-1-Flash-Cards

### ISSUE THREAD

**Issue by jacahn** [ga-dc/project1-gallery#29]
Link to repo: https://github.com/jacahn/Jac-Ahn-Project-1-Flash-Cards
Link to deployed app: https://jacahn.github.io/Jac-Ahn-Project-1-Flash-Cards/

Things you'd like specific feedback on: 
Resetting and randomizing questions.

**Comment by andrewsunglaekim** [comment]
👍 check ur inbox for my PR
