### ISSUE TITLE
Thomas Ferullo Hangman F3RULLO8

### ISSUE THREAD

**Issue by F3RULLO8** [ga-dc/project1-gallery#291]
Link to repo: https://github.com/F3RULLO8/project-1-hangman
Link to deployed app:
https://f3rullo8.github.io/project-1-hangman/
Things you'd like specific feedback on:

**Comment by dmc2015** [comment]
" Could add space between attributes  	1.	img id ="stick"src="hangman-66 
	2.	
 img elements should have an alt attribute  https://validator.w3.org/nu/?doc=https%3A%2F%2Ff3rullo8.github.io%2Fproject-1-hangman%2F   you should put your assets (images) in an asset folder   you should use “()” to controller your order of operations and make your code clearer regarding what is happening in the operation and when. “()” things in side of this will be evaluated first.  Example: 
                if (inputLetter.value === boxLetter && usedLetterArray.includes(inputLetter.value) === false) {

This would of been a good project to use OOP, it be cool for your portfolio if you had a functional approach (like this one) and then OOP. ***if you have the time and finish other projects/work  Example classes:  Word Score Figure   Don’t forget your ‘;’ in css  body {

    text-align: center;

    background: rgb(195, 228, 255);

    font-family: Arial, Helvetica, sans-serif

}  
you have a for loop that goes from 19 to 57, it isn’t really ideal. You could see if everything really needs to be in the loop, and then you could abstract some of them to functions to make it a little clearer.  I try not to have more than 2 nested loops and not more than 2 nested ifs, that is a little strict though. This will make your code easier to read and maintain though "
