### ISSUE TITLE
DavidZ Project 1

### ISSUE THREAD

**Issue by DavidZafa** [ga-dc/project1-gallery#292]
Link to repo: https://github.com/DavidZafa/DavidZafirovicProject1
Link to deployed app:https://davidzafa.github.io/DavidZafirovicProject1/

Things you'd like specific feedback on:
I feel like what I did was too simple. Would love to know what I could've added in terms of functionality/styling.

Was my code well organized? Was it as simple as it could be?

**Comment by dmc2015** [comment]
looks like you have an image not available for mj

**Comment by DavidZafa** [comment]
Uhm yeah, apparently whoever was hosting that image took it down? I went to the url and yeah, image isn't available.

**Comment by dmc2015** [comment]
Ok, that's fine. Thought about saving it to your project?

**Comment by DavidZafa** [comment]
I’m gonna actually do that right now, haven’t been to home to do so since now. Also, do I know my score, or just that I passed?
