### ISSUE TITLE
Project 1: Hangman (Erin Kelley)

### ISSUE THREAD

**Issue by erinkelley27** [ga-dc/project1-gallery#293]
Link to repo: https://github.com/erinkelley27/project1-hangman/tree/gh-pages
Link to deployed app: https://erinkelley27.github.io/project1-hangman/

Things you'd like specific feedback on:
-Are my if else statements for what happens when an incorrect letter is submitted DRY enough? Is there a better way?

**Comment by dmc2015** [comment]
some of the logic could be restructured in the js file, good work overall
