### ISSUE TITLE
GAME-WDI-DC-2018-LAWRENCE-KIRK 

### ISSUE THREAD

**Issue by lmkirkiii** [ga-dc/project1-gallery#296]
Link to repo: https://github.com/lmkirkiii/-GAME-WDI-DC-2018
Link to deployed app: https://lmkirkiii.github.io/-GAME-WDI-DC-2018/

Things you'd like specific feedback on:
A couple things that came up for me through this process. 

//VALIDATOR 

First of all I validated HTML and CSS but some of the things the validator said were incorrect. For example it told me I could not use a justify-content: space-evenly quality for my styles.css and they were wrong. Second in the HTML when I tried adding unseen filler content in my tags to satisfy the validators error that tags were left empty it filled up my tags visibly so I deleted it. 

//WET CODE

I still really feel like I need help on seeing how to better dry out my code. I found that I have bad habits of getting things done but with too much repetition

**Comment by dmc2015** [comment]
don't worry about the validator too much. it seems to be outdated.
