### ISSUE TITLE
Stephanie Choi - Project 1 (Simon Says)

### ISSUE THREAD

**Issue by jsc397** [ga-dc/project1-gallery#297]
Link to repo: https://github.com/jsc397/Project1-Simonsays/tree/gh-pages
https://github.com/jsc397/Project1-Simonsays/tree/dev
Link to deployed app: https://jsc397.github.io/Project1-Simonsays/

Things you'd like specific feedback on:
How do I compare user clicks to answerArray.
How would I possibly use a higher-order function to re-write the Node.List loop.

**Comment by dmc2015** [comment]
I graded this, it is considered incomplete. to complete it you would basically need the simon logic for the game working. We can go over additional feedback at another point. I am just trying to get grades out at the moment.

**Comment by jsc397** [comment]
Hey guys,
Updated my bronze package Simon says
Project One COMPLETE! (hopefully)!!!!!
@ @dmc2015
