### ISSUE TITLE
Get to Know Sean

### ISSUE THREAD

**Issue by SeanTay** [ga-dc/project1-gallery#3]
Link to repo: https://github.com/SeanTay/flash-cards
Link to deployed app: http://seantay.github.io/flash-cards/

Things you'd like specific feedback on:  Recommendation on shortening my code.  Any approach we can take from the start to keep it short.

**Comment by RobertAKARobin** [comment]
# Project Feedback + Evaluation

| Score | Expectations |
| --- | --- |
| 0 | Incomplete |
| 1 | Progressing |
| 2 | Performing |
| 3 | Excelling |

## Project Workflow: 2

> Did you complete the user stories, wireframes, task tracking, and/or ERDs, as specified above? Did you use source control as expected for the phase of the program you’re in?

## Technical Requirements: 2

> Did you deliver a project that met all the technical requirements? Given what the class has covered so far, did you build something that was reasonably complex?

## Code Quality: 1

> Did you follow code style guidance and best practices covered, such as spacing, modularity, and semantic naming? Did you comment your code?

## Creativity/Interface: 2

> Is your user interface easy to use and understand? Does it make sense for the problem you're solving? Does your interface demonstrate creative design?

## Overall: 2

My code comments: https://github.com/SeanTay/flash-cards/pull/2/files

Nice job, Sean! I think your code is pretty DRY: I don't see a whole lot that repeats.

I think the big thing you need to watch out for is code style -- being consistent with indentation, spacing, semicolons, and so on.

One thing that might be helpful is whenever you have an `if/else` with a big wall of code inside it, take each `if` chunk and put it into its own function. That makes it much easier to see how things "flow" through the `if/else`.
