### ISSUE TITLE
Simon-Marc Fournier

### ISSUE THREAD

**Issue by mfournier91** [ga-dc/project1-gallery#30]
Link to repo: https://github.com/mfournier91/Simon
Link to deployed app: https://mfournier91.github.io/Simon/

Things you'd like specific feedback on: On the deployed app, the page won't allow the cdn that I used for my animation library. 
`Mixed Content: The page at 'https://mfournier91.github.io/Simon/' was loaded over HTTPS, but requested an insecure script 'http://cdnjs.cloudflare.com/ajax/libs/gsap/1.18.4/TweenMax.min.js'. This request has been blocked; the content must be served over HTTPS`

**Comment by andrewsunglaekim** [comment]
👍  Great work, check my PR for rubric and comments
