### ISSUE TITLE
Banana Trivia - Courtney Seitz

### ISSUE THREAD

**Issue by Courtney-Seitz** [ga-dc/project1-gallery#34]
Link to repo: https://github.com/CourtneySeitz/Trivia/tree/gh-pages (master branch is old game)
Link to deployed app: http://courtneyseitz.github.io/Trivia/

Things you'd like specific feedback on:
Some of my CSS did not pass validation, yet I did not understand why as all was working and seemed valid. Wondering why this is.

**Comment by Courtney-Seitz** [comment]
Merge of master (old game from old cohort) with gh-pages (new game) doesn't seem to be updating here. It is updated within my local git repository, but for some reason not here on github.

**Comment by nayana487** [comment]
Total: 7/12 

Project Workflow: 1/3 - Nice job with the wireframing, though I'd encourage you to flesh it out a little more in the future. I'd also flesh out the pseudocode. Also, I'd include a readme file with a general overview of the project, approach taken with technologies used, key features and next steps. 

Technical Requirements: 2/3 - All your functionality seems to work, but I'd encourage you to use more of the techniques you learned in class to challenge yourself such as DOM traversal methods. What errors did you see in the validator with your CSS? I ran your code through the W3C one and it didn't turn up any errors for me.  

Code Quality: 2/3 - Your code is formatted nicely and the comments here are easy to follow along with. Couple questions though: why did you only put the first four lines in the document ready function and I'm curious about this bit: 

//jQuery variable
$question = $('.question');

Doesn't seem like you needed to make this a variable and you don't use it in line 26. 

Creativity: 2/3 - The design is clean and easy to follow, but it looks like the user is able to select multiple options. Might be something you want to tackle in the future.
