### ISSUE TITLE
Logan Leopold's Project 1

### ISSUE THREAD

**Issue by LoganLeopold** [ga-dc/project1-gallery#343]
Link to repo: https://github.com/LoganLeopold/Trivia
Link to deployed app: https://loganleopold.github.io/Trivia/

Things you'd like specific feedback on: 

I think the main point of frustration and curiosity for the app is its fragility. I found so many bugs I had to fish out and flush just playing it through 20 times the last hour. A simple issue like calling a function that's dependent on incrementing a variable _before_ I'd incremented it would've made me look silly if I hadn't decided to play my game through again, found it, and fixed it. Are there general guiding principles for assuring code isn't so breakable or is that just the name of the game and fighting those issues now will remind us of them as potential sources of trouble for later (I'm sure there's some of this, but any axioms are appreciated!)?

**Comment by erinkelley27** [comment]
Great job on this Logan! I have marked it complete in Garnet.
Learning how to debug and write clean, dry and efficient code is just part of the process of becoming a developer. It sounds like the process of of building your project gave you a lot of great practice! As time goes it, this will become easier and more intuitive. Good work!!
