### ISSUE TITLE
Gio Project1 - Hangman

### ISSUE THREAD

**Issue by GioSilva** [ga-dc/project1-gallery#36]
Link to repo: https://github.com/GioSilva/Project1---Hangman
Link to deployed app: https://giosilva.github.io/Project1---Hangman/

Things you'd like specific feedback on: 
- Other solution routes
- Is there a faster approach using functions?
- How to add animation to the images so it actual looks like the hangman is getting drawn as the game progresses? Was looking for jq plugins but couldn't find one that does this, although I'm sure there must be!

**Comment by nayana487** [comment]
Total: 7/12 

Project Workflow: 1/3 - You have a good start here, but I'd encourage you to flesh out your readme a lot more with a general intro of what the project is, the approach taken with technologies included, key features and next steps. I'd include some wireframes as well. 

Technical Requirements: 2/3 - You did a nice job here of challenging yourself and implementing a good amount of techniques you were taught in class. I'd encourage you to push yourself some more and try out DOM traversal methods. 

Code Quality: 2/3 - Your code is formatted nicely and commented well throughout. You also did a nice job naming your variables. I'd encourage you to put your files in folders to organize a little better--a css file for your stylesheets, a js folder for your scripts and a planning folder for wireframes, user stories, etc.

Creativity: 2/3 - You obviously are working with some challenging CSS here and you mostly execute it successfully, but there are some hiccups in the layout with the numbers appearing above the dash lines--they seem to go a little too far to the left. 

Questions: Your first two questions are pretty broad, let me know if you have something specific in mind and we can take a look. As for the third question, they is probably a way to do that in CSS but it's definitely a super advanced solution that you'd likely have to be a master to implement. I'm sure most would use some kind of animation software to actually implement this. There may be a plugin, but I'm not familiar with one.
