### ISSUE TITLE
simon

### ISSUE THREAD

**Issue by curranbriant** [ga-dc/project1-gallery#362]
Link to repo:https://github.com/curranbriant/simon
Link to deployed app: curranbriant.github.io-simon

Things you'd like specific feedback on:
why the heck my blink/active function wont work

**Comment by curranbriant** [comment]
link deployed app - https://jolly-newton-e74653.netlify.com/
repo - https://github.com/curranbriant/simon  :)

**Comment by tomatohammado** [comment]
Awesome job! We'll send out the full grades via email so look out for that.
