### ISSUE TITLE
Taylor Edwards Project 1 (7/14/16)

### ISSUE THREAD

**Issue by ghost** [ga-dc/project1-gallery#37]
Link to repo:
https://github.com/tedwards1884/Towers-of-Hanoi
Link to deployed app:
https://tedwards1884.github.io/Towers-of-Hanoi/

Things you'd like specific feedback on:

Honestly, I was able to accomplish just about all of the objectives I set out for myself in terms of utility / interactivity - obviously there's a lot still to do with styling. I found myself several times throughout wishing I had planned things better or taken a different approach; more than once I felt like I was resorting to a brute force method.

I guess I'm most interested to know a) how I can improve the interface / presentation, and b) where in my code you see potential for better / more efficient solutions as I head into refactoring.

**Comment by andrewsunglaekim** [comment]
Great work Taylor! Let me know if you have any questions/comments about the rubric or comments I've made in your repo. 👍
