### ISSUE TITLE
Sarah Shultis project 1 feeding frenzy

### ISSUE THREAD

**Issue by skshultis** [ga-dc/project1-gallery#38]
Link to repo: https://github.com/skshultis/Project1.git
Link to deployed app: https://skshultis.github.io/Project1 

Things you'd like specific feedback on: I felt like my code was disorganized. My project functions well but is unexciting for the user.

**Comment by nayana487** [comment]
Total: 8/12

Project Workflow: 2/3 - It looks like you got mostly what you wanted to provide your users out of the app, so nice job there! I'd flesh out the ReadMe more with a list of key features and include your user stories there. Additionally, in the future, it'd be helpful to draw out a few sketches of your project before you write the code. 

Technical Requirements: 2/3 -In the next round, I'd like to see you employ more methods. You use the find method a good deal but challenge yourself to play around with more. Also, would be cool to see you implement more DOM traversal methods here. That said, you've implemented a good deal of functionality and I'm glad to see you've gotten much better with your conditionals. 

Code Quality: 1/3 - You commented out a bracket in your main.js line 52, which I'm sure is contributing to a bug somewhere. Be careful with that! Also be more mindful of your spacing. For example, the functions should all be lined up at the same level. Also, don't leave dead code you're not using in your app. It'd also be helpful to include more comments in your code. 

Creativity: 3/3 - This was a fun, visually pleasing app! I really enjoyed going through your game and definitely accomplished what you set out to do.
