### ISSUE TITLE
project_1 Simon game (Melika Rasti)

### ISSUE THREAD

**Issue by mrasti** [ga-dc/project1-gallery#380]
Link to repo: https://github.com/mrasti/simongame
Link to deployed app: https://mrasti.github.io/simongame/

Things you'd like specific feedback on:
I will update the project documentation later. I will be happy to have feedback about that.

**Comment by ellisonr** [comment]
I didn't get to check this out during the presentations. This is awesome!

**Comment by mrasti** [comment]
@ellisonr : Thank you Ellison for checking my project. :)
