### ISSUE TITLE
Ellison Rio (Project #1, The Office Trivia)

### ISSUE THREAD

**Issue by ellisonr** [ga-dc/project1-gallery#383]
Link to repo: https://github.com/ellisonr/the-office-trivia
Link to deployed app: https://ellisonr.github.io/the-office-trivia/

Things you'd like specific feedback on:
*I would've liked to make it so the questions were just coming in one at a time / sliding across the screen. But, with my very late pivot to the trivia option, I only had about 6-8 hours to get this thing done with all the requirements met.
*My cognitive space feels like it's up to the brim right now, so I can't even think of what I'd like specific feedback on... maybe just general commentary on the logic, dryness of the code, any improvements/tips you may have for me at first glance of how my code is set up.

*I've also included the repo and deployed app for my initial effort which was for a hangman game - 
Hangman repo: [https://github.com/ellisonr/the-office-hangman](url)
Hangman deployed: [https://ellisonr.github.io/the-office-hangman/](url)

**Comment by mrasti** [comment]
I also did not get to check your project in presentation time. It has turned out fun. I like how you created your layout using image thumbnails.
