### ISSUE TITLE
Project 1 Trivia (Jordan Mittelman)

### ISSUE THREAD

**Issue by jmittelman** [ga-dc/project1-gallery#386]
Link to repo: https://github.com/triplespice/Project-1-Trivia
Link to deployed app: https://triplespice.github.io/Project-1-Trivia/

Things you'd like specific feedback on:

opportunities to consolidate/ refactor my code to make it more concise
scoring glitch that skips score on first correct answer but then counts thereafter

**Comment by tomatohammado** [comment]
Great work making the updates to your project! It's currently marked as fully complete, awesome job!
