### ISSUE TITLE
Project One Chris Phillips

### ISSUE THREAD

**Issue by ghost** [ga-dc/project1-gallery#39]
Link to repo: https://github.com/chris-A-phillips/reactingToSimon
Link to deployed app: https://chris-a-phillips.github.io/reactingToSimon/

Things you'd like specific feedback on: I really want to go through James' solution and understand how he approached it since it's way different than what I did.

**Comment by nayana487** [comment]
Total: 10/12

Project Workflow: 2/3 - You have a lot of great information in your readme, but it's kind of scattered and you have to jump around a bit to get a sense of what's going on. It's helpful to start with a high-level explanation of what the project is, then talk about your approach in implementing including technologies used, key features and next steps. Also love that you included instructions for contributing =)

Technical Requirements: 3/3 - Love that your implemented sound here! Very cool that once again you're teaching yourself something new. That's an awesome trait for a dev. Also, timer functions are super hard to work with but you did a solid job here. I think there's a little too much lag time between when you get an answer wrong and the alert message comes up, but that's not a huge deal.  Also, what's the insane button supposed to do? Didn't see anything in the code. Is that something you're adding later?

Code Quality: 2/3 - Your code is really nicely laid out and spaced, but it would have been really helpful if you included inline comments to explain the functionality more. It's also good practice to have folders organizing your files--a CSS folder for all your stylesheets, a JS folder for all your scripts, and a planning folder where you can include your wireframes, pseudocode, etc. 

Creativity: 3/3 - This was a very fun game with a really nice interface. You clearly put a lot of thought into the user experience here. Bonus points for the Hobbes favicon.

**Comment by ghost** [comment]
Whoops! The refactor.js is the actual final product! That's where the memory persistence, insane button, and other functionality from my final presentation were coded.
