### ISSUE TITLE
Josh Neves : Project 4 - Trivia Game

### ISSUE THREAD

**Issue by joshseven** [ga-dc/project1-gallery#433]
Link to repo: https://github.com/joshseven/trivia_game
Link to deployed app: https://joshseven.github.io/trivia_game/

Things you'd like specific feedback on:

**Comment by dcartist** [comment]
Good Job!

![dragonmario](https://user-images.githubusercontent.com/21227957/70176711-f17b6700-16a6-11ea-9465-1fd06927faeb.gif)
