### ISSUE TITLE
Ashley Taylor [Project#1 Game]

### ISSUE THREAD

**Issue by dynasty2** [ga-dc/project1-gallery#434]
Link to repo: https://github.com/dynasty2/game
Link to deployed app: https://dynasty2.github.io/game/

Things you'd like specific feedback on:

The "ghost lines" that show up.
Making javascript more DRY. (i.e. inserting the photos via js)
An "intro" page that transitions into the game space.

**Comment by dcartist** [comment]
Good Morning and Good Job!
![dragonmario](https://user-images.githubusercontent.com/21227957/70176522-a19ca000-16a6-11ea-8436-cea3c0273737.gif)
