### ISSUE TITLE
Wassim [HangMan]

### ISSUE THREAD

**Issue by LLwassim** [ga-dc/project1-gallery#438]
Link to repo: https://github.com/LLwassim/HangMan
Link to deployed app: https://llwassim.github.io/HangMan/

Things you'd like specific feedback on:

APEMODE and multi game mode functions are broken not quite sure whats wrong

**Comment by dcartist** [comment]
Good job!
![dragonmario](https://user-images.githubusercontent.com/21227957/70176022-baf11c80-16a5-11ea-886b-2596ee07c135.gif)
