### ISSUE TITLE
Noah Clark

### ISSUE THREAD

**Issue by clarknoah** [ga-dc/project1-gallery#439]
Link to repo: [Github Url](https://github.com/clarknoah/memoreyes)
Link to deployed app: [Memoreyes Deployed Page](https://clarknoah.github.io/memoreyes/index.html)

Things you'd like specific feedback on:

**Comment by dcartist** [comment]
Good Job!
![dragonmario](https://user-images.githubusercontent.com/21227957/70175947-9eed7b00-16a5-11ea-99d9-1a288e4f388c.gif)
