### ISSUE TITLE
Bola Adebesin

### ISSUE THREAD

**Issue by MobolanleAdebesin** [ga-dc/project1-gallery#440]
Link to repo: https://github.com/MobolanleAdebesin/trivia-game
Link to deployed app: https://mobolanleadebesin.github.io/trivia-game/

Things you'd like specific feedback on:

Ways to improve the game logic

**Comment by dcartist** [comment]
Good Job
![mortalKombat](https://user-images.githubusercontent.com/21227957/70175218-4e295280-16a4-11ea-8a67-41d702dc5be1.gif)
