### ISSUE TITLE
Cards.OmMyGod.com

### ISSUE THREAD

**Issue by karadikid** [ga-dc/project1-gallery#441]
Link to repo: https://github.com/karadikid/flash-cards
Link to deployed app: http://cards.ommygod.com

Things you'd like specific feedback on:
So close to doing a few more things:

1. - Verifying that a card is flipped by checking the existence of an element.
2. - Adding some scoring.

**Comment by karadikid** [comment]
Had User Experience Tester evaluate.

Iterated:
Created new animations and added visible scoring for the user.

Also added answer display when the user gets the question wrong!

Whoo hoo!

**Comment by mrrogercampbell** [comment]
Hey the game looks great! I like the effects that you added and the wasted video. Great job on deployment also. 

Marking this as complete
