### ISSUE TITLE
AlexG Simon Game Project

### ISSUE THREAD

**Issue by AGarcia85** [ga-dc/project1-gallery#442]
Link to repo: git@github.com:AGarcia85/Unit-project1.git
Link to deployed app: https://agarcia85.github.io/Unit-project1/.

Things you'd like specific feedback on: 
I still couldn't figure out how to get a separate order list for the computer turns. Also I would like feedback on my coding and how it could be better because I feel like its not clean or condensed enough at my skill level to make it work properly. I would like Feedback on my CSS styling too because I feel like it could be way better than it is now.

**Comment by mrrogercampbell** [comment]
The game looks amazing and plays very well. 

In all honesty you did a very good job making the code clean and dry. I only have a few suggestions when it comes to cleaning it up. Which are as follows:
- Define games start variable values when you initial create them on line 11-19
- Clear out the console.logs if they are no longer needed
- You could potentially store the the color style in variables: `let redStyle = red.style` then you could do `redStyle.backgroundColor = 'red'` `redStyle.border = etc…`

In regards to you wanting a separate order list for the computer turns, I am not sure what you mean. When we get back next week lets sit down and take a look at this together. 

I am marking this as complete.
