### ISSUE TITLE
Jenny Trivia Game

### ISSUE THREAD

**Issue by jmripper** [ga-dc/project1-gallery#443]
Link to repo: https://github.com/jmripper/National_Parks_Trivia
Link to deployed app: https://jmripper.github.io/National_Parks_Trivia/

Things you'd like specific feedback on:
If there was a way for code to be more 'dry' and any other improvements. Still working on getting the images in as well.

**Comment by mrrogercampbell** [comment]
Hey your game is not rendering. I am able to see the background picture and the white box where the text should be but other than that no game logic is rendering. Take a look and let me know when it is working. 

For now I am marking this as incomplete, resubmission will be due: 1/6/20

**Comment by jmripper** [comment]
@rc1336 This should be complete now. Not sure how to tag Paula to rereview it.

**Comment by jmripper** [comment]
@dcartist My game is good to review. Thanks

**Comment by dcartist** [comment]
Good job!
<img src="https://media.giphy.com/media/WKdWA04KRn58A/giphy.gif"/>
