### ISSUE TITLE
Igor Slabykh. project_4_trivia

### ISSUE THREAD

**Issue by Cherezmz** [ga-dc/project1-gallery#444]
Link to repo: https://github.com/Cherezmz/project_4_trivia
Link to deployed app: https://cherezmz.github.io/project_4_trivia/ 

Things you'd like specific feedback on:

the app was not deployed properly.

**Comment by mrrogercampbell** [comment]
Hey the game looks great! I was able to see it via the deployed link provided. 

I am marking this as complete.
