### ISSUE TITLE
Michael Driscoll Unit-1-Project: Trivia Game

### ISSUE THREAD

**Issue by mdrisco4** [ga-dc/project1-gallery#445]
Link to repo: https://github.com/mdrisco4/Unit-Project-1
Link to deployed app: https://mdrisco4.github.io/Unit-Project-1/

Things you'd like specific feedback on: Getting better on cleaning up code.  Debugging as things get more and more complex.  Overall impressions.

**Comment by mrrogercampbell** [comment]
Hey the game looks great! The animations and effects you used are really cool. I am glad you took the time to explore it. 

**I am marking this as complete.** 

#### Feedback:
- I would clean up the ReadMe, right now it just looks like a block of text.* Add some markdown templating to clean it up some.
- Overall the game looks really cool and plays well. I would suggest possibly changing the background or adding a light opacity to bring down the brightness it is somewhat hard for me to look at for a long period of time. But that could just be my sensitive eyes. 
- I would suggest cleaning up the files that are commented out. If you need to keep them for later possibly create a scratch directory and place all unneeded code there.
- Most definitely should put all your querySelectors into variables, no reason to see `document.` something all over the place. 
- I would clean up the ReadMe, right now it just looks like a block of text.* Add some markdown templating to clean it up some.
- Overall the game looks really cool and plays well. I would suggest possibly changing the background or adding a light opacity to bring down the brightness it is somewhat hard for me to look at for a long period of time. But that could just be my sensitive eyes. 
- I would suggest cleaning up the files that are commented out. If you need to keep them for later possibly create a scratch directory and place all unneeded code there.
- Most definitely should put all your querySelectors into variables, no reason to see `document.` something all over the place.
