### ISSUE TITLE
Mamady Sillah Unit 1 Project

### ISSUE THREAD

**Issue by mamady310** [ga-dc/project1-gallery#447]
Link to repo:  git@github.com:mamady310/Unit-1-project.git
Link to deployed app:   https://mamady310.github.io/Unit-1-project/.

Things you'd like specific feedback on:
All things CSS. I could not get the text in the cards to be centered

**Comment by mrrogercampbell** [comment]
The game looks god. Also the card seem centered to me. One suggestion I would make is that when you change the screen size the background image goes from `stretch` to `tile`. Should be a quick fix with a media query. 

Marking this as complete.
