### ISSUE TITLE
Adam DeLessio - Project 1

### ISSUE THREAD

**Issue by Adam-DeLessio** [ga-dc/project1-gallery#449]
Link to repo:
https://github.com/Adam-DeLessio/Tower_of_Hanoi

Link to deployed app:
https://adam-delessio.github.io/Tower_of_Hanoi/

Things you'd like specific feedback on:

**Comment by mrrogercampbell** [comment]
Game look great! Really nice job on the css. The responsiveness also looks good.

Marking this as complete.
