### ISSUE TITLE
Chase Freeman Project 1 

### ISSUE THREAD

**Issue by chaseTfreeman** [ga-dc/project1-gallery#45]
Repo Link: https://github.com/chaseTfreeman/ctf_hanoi
Live link: https://chasetfreeman.github.io/ctf_hanoi/

Thanks! Sorry for not posting it sooner! Also, sorry for the lack of decent aesthetics.

**Comment by andrewsunglaekim** [comment]
Great job chase 👍  Read comments/rubric in the PR I've submitted to your repo. Let me know if you have any questions/concerns.
