### ISSUE TITLE
Robert Baer Project 1

### ISSUE THREAD

**Issue by robertsbaer** [ga-dc/project1-gallery#450]
Link to repo: https://github.com/robertsbaer/trivia
Link to deployed app: https://robertsbaer.github.io/trivia/

Things you'd like specific feedback on:
Not Sure yet

**Comment by mrrogercampbell** [comment]
Game looks great. I would suggest adding a instructions to like the top of the game to let people know it is a self scoring game. 

Marking this as complete.
