### ISSUE TITLE
Jose- Unit 1 project 

### ISSUE THREAD

**Issue by jcasado6** [ga-dc/project1-gallery#451]
Link to repo: https://github.com/jcasado6/Spanish-Flashcards-Project
Link to deployed app: https://jcasado6.github.io/Spanish-Flashcards-Project/

Things you'd like specific feedback on: Everythinggg

**Comment by mrrogercampbell** [comment]
Game looks great! Not sure what all feedback to give other than the lag that you have when you hover over the cards without diving into the code fully I am not sure what could be causing it. If you'd like we can find sometime next week to look at it more in depth at office hours.

Marking this as complete.
