### ISSUE TITLE
Matt's Project

### ISSUE THREAD

**Issue by vmipfdr** [ga-dc/project1-gallery#452]
Link to repo: https://github.com/vmipfdr/GA-Game-Project-1
Link to deployed app: https://vmipfdr.github.io/GA-Game-Project-1/. 

Things you'd like specific feedback on:

**Comment by llucas314** [comment]
Good job! Also, [here](https://www.quicksprout.com/website-usability/) is a good article for improving user experience when building sites.

Make sure you use the [CSS validator](https://jigsaw.w3.org/css-validator/).

**Comment by vmipfdr** [comment]
@llucas314 I did, and the way we were taught grids locations, they wanted us to do span, so as a way of encouraging muscle memory, I retained the span content
