### ISSUE TITLE
Sara [Tower of Hanoi]

### ISSUE THREAD

**Issue by saralaffin** [ga-dc/project1-gallery#453]
Link to repo: https://github.com/saralaffin/front-end-game-tower-of-hanoi
Link to deployed app: https://saralaffin.github.io/front-end-game-tower-of-hanoi/

Things you'd like specific feedback on:
Readability/code comments
Other than that broad topic, nothing specific, but will appreciate all feedback!

**Comment by llucas314** [comment]
@saralaffin Good job! Very readable code. Check out [this](https://www.geeksforgeeks.org/7-tips-to-write-clean-and-better-code-in-2020/) article for more info on commenting.
