### ISSUE TITLE
Levani's Project 4 - Trivia Game

### ISSUE THREAD

**Issue by Levani1111** [ga-dc/project1-gallery#455]
Link to repo: https://github.com/Levani1111/Trivia
Link to deployed app: https://levani1111.github.io/Trivia/

Things you'd like specific feedback on:

**Comment by llucas314** [comment]
@Levani1111 Good job!  I would work on enhancing your readme.

**Comment by Levani1111** [comment]
@llucas314 Thank you for your feedback.  I have updated the readme.  Please let me know if I need to do anything else.

**Comment by Levani1111** [comment]
@ZakkMan 
I am sending this to you again because it hasn't been closed, but I haven't reviewed any feedback.  Thanks.
