### ISSUE TITLE
Front-End Game Trivia

### ISSUE THREAD

**Issue by sarahtsige** [ga-dc/project1-gallery#457]
Link to repo: https://github.com/sarahtsige/Trivia-Game
Link to deployed app: https: //sarahtsige.github.io/Trivia-Game/

Things you'd like specific feedback on:

**Comment by llucas314** [comment]
Good job! I liked this game a lot. 

Suggestions:
* Keep working on responsiveness
* Stop users from clicking multiple answers
* Remove code that has been commented out
* Beef up the readme too
