### ISSUE TITLE
Hangman Game

### ISSUE THREAD

**Issue by zfriendly** [ga-dc/project1-gallery#458]
Link to repo: https://github.com/zfriendly/hangman-game
Link to deployed app: https://zfriendly.github.io/hangman-game/

Things you'd like specific feedback on: Responsiveness, how to add animation.

**Comment by llucas314** [comment]
@zfriendly Awesome sauce! I would remove the code that has been commented out. Also, the random word generator is not working. The API key is throwing errors.
