### ISSUE TITLE
Front-End Game: Simon

### ISSUE THREAD

**Issue by caioingber** [ga-dc/project1-gallery#459]
Link to repo: https://github.com/caioingber/simon-says
Link to deployed app: https://caioingber.github.io/simon-says/

Things you'd like specific feedback on: Utilizing classes & OOP to create more DRY code. Utilizing setTimeout function more efficiently

**Comment by 0xZakk** [comment]
@caioingber This looks amazing! This is definitely one of the better implementations of this that I've seen. Really, really great work here!
