### ISSUE TITLE
Rasheeda Alexander's Simon

### ISSUE THREAD

**Issue by RasheedaAlexander** [ga-dc/project1-gallery#46]
Link to repo: https://github.com/rasheedaalexander/Simon
Link to deployed app: https://rasheedaalexander.github.io/Simon

Need feedback on: 

I'd like to figure out a way to track the user's to interaction with game. I think it will take more research but any suggestions you have are welcome!

**Comment by andrewsunglaekim** [comment]
👍 Good work rasheeda. Check my PR for comments and rubric.
