### ISSUE TITLE
Colleen Frontend Project (initially submitted in wrong place sorry)

### ISSUE THREAD

**Issue by colleenobrien3** [ga-dc/project1-gallery#462]
Link to repo: https://github.com/colleenobrien3/Villanova-Bball-Trivia
Link to deployed app: https://colleenobrien3.github.io/Villanova-Bball-Trivia/

Things you'd like specific feedback on: Let me know please if i need to do anything else for it to be considered complete/ turned in.

@ZakkMan

**Comment by 0xZakk** [comment]
@colleenobrien3 Thanks! This looks really amazing! Really great work. This is so dope.

Minus the Villanova part. 😊
