### ISSUE TITLE
Project #1 Hangman ( Mike Rubin )

### ISSUE THREAD

**Issue by merubin** [ga-dc/project1-gallery#49]
Link to repo: https://github.com/merubin/hangman
Link to deployed app: https://merubin.github.io/hangman/

Things you'd like specific feedback on:
Need help with styling.
letter tray and keyboard get lost with backgrounds.
Hardest part of this project for me was creating the .css and .html pages  That is what I felt most unsure about.
When I render this hosted program on my Iphone, the keyboard is left justified.  Not sure why?

![image](https://cloud.githubusercontent.com/assets/19254862/18714978/828eb26c-7fe5-11e6-836f-9ee0cd333060.png)

**Comment by jshawl** [comment]
https://gist.github.com/jshawl/d77912418d9d7601783be66d70855af4

Let me know if you have any questions!
