### ISSUE TITLE
Kevin Mahoney: Project 1-Flash Cards

### ISSUE THREAD

**Issue by kjmahoney** [ga-dc/project1-gallery#50]
Link to repo: https://github.com/kjmahoney/Flash-Cards
Link to deployed app: https://kjmahoney.github.io/Flash-Cards/

Things you'd like specific feedback on:

I was able to achieve the goals of my initial application. But I'd like to code smarter with more DRY. So any suggestions for more organized and efficient coding would be great!

**Comment by nolds9** [comment]
:+1: Please see feedback [here](https://github.com/kjmahoney/Flash-Cards/pull/1)
