### ISSUE TITLE
Poh Chuan Kuan(Project1-Trivia)

### ISSUE THREAD

**Issue by pohckuan** [ga-dc/project1-gallery#51]
Link to repo: https://github.com/pohckuan/project1
Link to deployed app:https://pohckuan.github.io/trivia/trivia

Things you'd like specific feedback on:
I would like to learn to add a countdown timer on the page with jQuery, and avoid DRY principle while writing the questions on the html file. 
And I just learned that if my html file has a name other than "index", I will need to add that file name to the end of my repo's name on the link too.

**Comment by nolds9** [comment]
:+1: Please see feedback [here](https://github.com/pohckuan/trivia/pull/1)
