### ISSUE TITLE
Project 1 - Hangman (Michael L)

### ISSUE THREAD

**Issue by MichaelZLai** [ga-dc/project1-gallery#52]
Link to repo: https://github.com/MichaelZLai/GA-Project-1
Link to deployed app: https://michaelzlai.github.io/GA-Project-1/

Things you'd like specific feedback on:
-If I need to reduce my javascript/jquery (in case I have unnecessary for, if or variables.
-Look and feel of the page. If it provides a good user experience (I'm all about the UX!)

**Comment by nolds9** [comment]
:+1: Please see feedback [here](https://github.com/MichaelZLai/GA-Project-1/pull/1)
