### ISSUE TITLE
 Mariana Lungu --FlashCards 

### ISSUE THREAD

**Issue by marlungu** [ga-dc/project1-gallery#54]
Link to repo:https://github.com/marlungu/FlashCards
Link to deployed app: https://marlungu.github.io/FlashCards/

Things you'd like specific feedback on: cosmetic

**Comment by jshawl** [comment]
Awesome job on the project! Let me know if you have any questions - https://gist.github.com/jshawl/dbc94d96400833f729764f793b112fa4
