### ISSUE TITLE
Khoi's Simon Game

### ISSUE THREAD

**Issue by khoitle** [ga-dc/project1-gallery#62]
Link to repo: https://github.com/KhoiLe89/GA-Project-1
Link to deployed app: https://khoile89.github.io/GA-Project-1/

Things you'd like specific feedback on:
-The length and organization of my code
-Any other way I could've done my JS functions

**Comment by nolds9** [comment]
:+1: Please see feedback [here](https://github.com/KhoiLe89/GA-Project-1/pull/2)
