### ISSUE TITLE
Mark Sweet Trivia (Project 1)

### ISSUE THREAD

**Issue by marks828** [ga-dc/project1-gallery#63]
Link to repo: https://github.com/SNESChalmers34/project1/tree/gh-pages
Link to deployed app: sneschalmers34.github.io/project1

Things you'd like specific feedback on: 
Nothing I can think of but I'm sure you'll have feedback that will be very helpful

**Comment by jshawl** [comment]
https://gist.github.com/jshawl/a3d4b6fe4244c9c83f35483c87627879

Let me know if you have any questions!
