### ISSUE TITLE
Billy Keating Project 1

### ISSUE THREAD

**Issue by bkeating55** [ga-dc/project1-gallery#64]
Link to repo: https://github.com/bkeating55/Project-1
Link to deployed app: https://bkeating55.github.io/Project-1/

Things you'd like specific feedback on:
Logic behind making questions appear individually via keystroke or clicking a next button
How to include score when incorrect answer is chosen

**Comment by nolds9** [comment]
:+1: Please see feedback [here](https://github.com/bkeating55/Project-1/pull/1)
