### ISSUE TITLE
Andrew Whitley - Project One (Towers of Hanoi)

### ISSUE THREAD

**Issue by AndyWhitley** [ga-dc/project1-gallery#65]
Link to repo: https://github.com/AWhitleyGA/towers_of_hanoi
Link to deployed app: https://awhitleyga.github.io/towers_of_hanoi/

Things you'd like specific feedback on:
1. How effectively did I structure my code, what could be improved on
2. Any places in the code where there would be a more efficient/elegant way to do something
3. Opinions on the presentation of the App, particularly how effective the UI is and the design

**Comment by jshawl** [comment]
https://gist.github.com/jshawl/d021e34664b7646b5fc2f2bcd7259693

Let me know if you have any questions!
