### ISSUE TITLE
Alexander Spottswood - Project 1

### ISSUE THREAD

**Issue by ajspotts** [ga-dc/project1-gallery#68]
Link to repo: https://github.com/ajspotts/Project-1
Link to deployed app: https://ajspotts.github.io/Project-1/

Things you'd like specific feedback on:
1. the functionality of the game i.e. how it plays
2. the quality of the javascript that was written to be evaluated

**Comment by jshawl** [comment]
https://gist.github.com/jshawl/0c1ae4780b39c66ffff421cb71b8f96e

Let me know if you have any questions!
