### ISSUE TITLE
Hangman Latoya Watson

### ISSUE THREAD

**Issue by LWatsonlm** [ga-dc/project1-gallery#70]
comfort: 3-4/5
complete: 4.5/5
https://github.com/LWatsonlm/project1
https://lwatsonlm.github.io/project1/

Features I'd like to add: 
First play can type in a hint. When the first player section disappears, hint section to appears
Not letting player two click on the same letter twice
Turning the letter red after clicking it

**Comment by jshawl** [comment]
https://gist.github.com/jshawl/7d62734e9f208546cf2b806dfb51cce7

Let me know if you have any questions!
