### ISSUE TITLE
Adina Does Flash Cards

### ISSUE THREAD

**Issue by adina-pollack** [ga-dc/project1-gallery#8]
Link to repo: https://github.com/adina-pollack/AdinaDoesFlashCards 
Link to deployed app: http://adina-pollack.github.io/AdinaDoesFlashCards/ 

Things you'd like specific feedback on:
Better ways to clean up my code. I tried breaking down my larger functions into pieces and making those their own functions, but it still seems as if I have the same amount of code lines.

**Comment by RobertAKARobin** [comment]
# Project Feedback + Evaluation

| Score | Expectations |
| --- | --- |
| 0 | Incomplete |
| 1 | Progressing |
| 2 | Performing |
| 3 | Excelling |

## Project Workflow: 2

> Did you complete the user stories, wireframes, task tracking, and/or ERDs, as specified above? Did you use source control as expected for the phase of the program you’re in (detailed above)?

## Technical Requirements: 2

> Did you deliver a project that met all the technical requirements? Given what the class has covered so far, did you build something that was reasonably complex?

## Code Quality: 2

> Did you follow code style guidance and best practices covered in class, such as spacing, modularity, and semantic naming? Did you comment your code?

## Creativity/Interface: 2

> Is your user interface easy to use and understand? Does it make sense for the problem you're solving? Does your interface demonstrate creative design?

## Overall: 2

This looks _great_, Adina!

`clean code != short code`. Usually the other way around, actually. I went through all your code but honestly didn't find much to change. One thing I like to do is "namespace" my functions. If I have a bunch of functions like this:

``` js
function updateTimer(){}
function clearTimer(){}
function createNewTimer(){}
```

...I'll nest them all inside an object. This lets me avoid writing `Timer` so many times, and tidies things up on the page as well.

``` js
var timer = {
  update: function(){},
  clear: function(){},
  create: function(){}
}
```

Then I can write `timer.update()` and so forth.

This is moving toward object-oriented Javascript, which we're introducing until this week.
